use spacetimedb::*;
use crate::{uuid_v7_uniq, now_micros};
use crate::auth::require_auth;
use crate::workspace::{check_space_access, workspace};
use crate::memory::{memory, memory_revision};
use crate::knowledge_graph::{kg_node, kg_edge, kg_community};
use crate::session::{session, agent_step};
use crate::message::message;
use crate::note::{note, note_backlink, note_revision};
use crate::profile::profile;
use crate::peer::peer;
use crate::context_compression::context_pack;
use crate::connector::connector_config;
use crate::context_directory::context_directory;
use crate::context_delta::delta_pack;
use crate::memory_feedback::peer_reputation;
use crate::retrieval::search_index;
use crate::hybrid_query::hybrid_result;
use crate::entity_extraction::entity_extraction_result;
use crate::memory::user_memory_result;
use crate::graph_traversal::{graph_traversal_result, shortest_path_result, bridge_result, kg_stats_result};
use crate::memory_feedback::memory_recommendation;

/// Generic result table for read queries against private tables.
///
/// Each query is scoped by `query_id` — the SDK generates a random token,
/// passes it to the reducer, then reads results filtered by that token.
/// This prevents cross-tenant data leakage through result tables.
#[table(accessor = query_result, public)]
#[derive(Debug, Clone)]
pub struct GenericQueryResult {
    #[primary_key]
    pub id: String,
    /// Token generated by the SDK to correlate request with response.
    #[index(btree)]
    pub query_id: String,
    /// The table being queried (for SDK disambiguation).
    pub table_name: String,
    /// JSON-serialized row data — all requested columns as a flat object.
    pub row_json: String,
    pub created_at: i64,
}

/// Whitelist of tables that can be queried through the generic endpoint.
/// Only these tables are accessible via `query_table`.
const ALLOWED_TABLES: &[&str] = &[
    "memory", "kg_node", "kg_edge", "kg_community",
    "session", "session_participant", "agent_step",
    "message", "note", "note_backlink", "note_block", "block_reference",
    "profile", "fact",
    "peer",
    "workspace", "space_permission",
    "document", "doc_chunk",
    "tag", "memory_tag",
    "insight", "mental_model",
    "entity_link",
    "change_event",
    "search_index",
    "tour", "tour_stop",
    "connector_config",
    "context_pack", "context_directory", "directory_memory_link",
    "context_entry",
    "context_delta_pack", // note: Rust struct is DeltaPack
    "context_delta",      // alias for context_delta_pack (SDK name)
    "directory",          // alias for context_directory (SDK name)
    "peer_reputation",
    "consolidation_log", "merge_suggestion",
    "memory_feedback", "workspace_config",
    "replication_peer", "replication_log",
    "hierarchy_cluster", "community_hierarchy",
    "proxy_metrics_snapshot",
    "bridge_result", "kg_stats_result", "memory_recommendation",
    "memory_revision",
    "note_revision",
    // Result tables (previously public, now private — queried through _query())
    "decrypted_memory_result",
    "user_memory_result",
    "hybrid_result",
    "entity_extraction_result",
    "api_key_result",
    "api_key_verification_result",
    "jwt_signing_key_result",
    "jwk_set_result",
    // P1 result tables (previously public, now private)
    "session_step_result",
    "user_session_result",
    "user_get_result",
    "session_search_result",
    "peer_summary_result",
    "space_member_result",
    "admin_list_result",
    "workspace_directory",
    "change_event_result",
    // P2 internal index tables (previously public, now private)
    "entity_search_index",
    "entity_term_index",
    "node_edge_index",
    "workspace_index",
    // MemFS tables (previously public, now private)
    "memfs_entry",
    "memfs_mount",
    "memfs_result",
    // Fact triple tables (previously public, now private)
    "fact_triple",
    "fact_triple_list_result",
    // Workspace result tables (previously public, now private)
    "workspace_context_result",
    "workspace_memory_stats_result",
    // Key rotation history (previously public, now private)
    "key_rotation_event",
    // Result tables read by the SDK through _query() (reducer-gated)
    "anomaly_result",
    "citation_result",
    "context_tree_result",
    "directory_content_result",
    "directory_result",
    "fact_result",
    "memory_tag_result",
    "observation_list_result",
    "peer_reputation_result",
    "profile_context_result",
    "replication_result",
    "review_result",
    "veracity_evidence_result",
    "webhook_list_result",
    "directive",
];

/// Query a private table with auth + workspace enforcement.
///
/// The SDK calls this instead of raw SQL. The caller must be authenticated.
/// For workspace-scoped tables, ``workspace_id`` must be non-empty and the
/// caller must have at least viewer access.
#[reducer]
pub fn query_table(
    ctx: &ReducerContext,
    query_id: String,
    table_name: String,
    workspace_id: String,
    filter_json: String,
    columns_json: String,
) -> Result<(), String> {
    let _account = require_auth(ctx)?;

    // Clean up stale results for this query_id before inserting new ones
    for old in ctx.db.query_result().query_id().filter(&query_id).collect::<Vec<_>>() {
        ctx.db.query_result().id().delete(&old.id);
    }

    // Validate table is whitelisted
    if !ALLOWED_TABLES.contains(&table_name.as_str()) {
        return Err(format!("Table '{}' is not queryable via this endpoint", table_name));
    }

    // If a workspace_id is provided, enforce space access
    if !workspace_id.is_empty() {
        check_space_access(ctx, &workspace_id, &ctx.sender().to_hex(), "viewer")?;
    }

    // Parse filter and columns
    let filter: serde_json::Value = serde_json::from_str(&filter_json)
        .map_err(|e| format!("Invalid filter JSON: {}", e))?;
    let columns: Vec<String> = if columns_json.is_empty() {
        vec![] // empty = all columns
    } else {
        serde_json::from_str(&columns_json)
            .map_err(|e| format!("Invalid columns JSON: {}", e))?
    };

    if !filter.is_object() {
        return Err("filter_json must be a JSON object".to_string());
    }

    let filter_obj = filter.as_object()
        .ok_or_else(|| "filter must be a JSON object".to_string())?;
    let now = now_micros(ctx);

    // ── Route to table-specific query logic ──────────────────────────
    match table_name.as_str() {
        "memory" => query_memory(ctx, query_id, workspace_id, filter_obj, &columns, now),
        "kg_node" => query_kg_node(ctx, query_id, workspace_id, filter_obj, &columns, now),
        "kg_edge" => query_kg_edge(ctx, query_id, workspace_id, filter_obj, &columns, now),
        "kg_community" => query_kg_community(ctx, query_id, workspace_id, filter_obj, &columns, now),
        "session" => query_session(ctx, query_id, workspace_id, filter_obj, &columns, now),
        "message" => query_message(ctx, query_id, filter_obj, &columns, now),
        "note" => query_note(ctx, query_id, workspace_id, filter_obj, &columns, now),
        "note_backlink" => query_note_backlink(ctx, query_id, workspace_id, filter_obj, &columns, now),
        "profile" => query_profile(ctx, query_id, workspace_id, filter_obj, &columns, now),
        "peer" => query_peer(ctx, query_id, workspace_id, filter_obj, &columns, now),
        "workspace" => query_workspace(ctx, query_id, filter_obj, &columns, now),
        "agent_step" => query_agent_step(ctx, query_id, workspace_id, filter_obj, &columns, now),
        "context_pack" => query_context_pack(ctx, query_id, workspace_id, filter_obj, &columns, now),
        "connector_config" => query_connector_config(ctx, query_id, workspace_id, filter_obj, &columns, now),
        // Aliases for SDK table names
        "directory" => query_generic_scan(ctx, &query_id, "context_directory", workspace_id, filter_obj, &columns, now),
        "context_delta" => query_generic_scan(ctx, &query_id, "delta_pack", workspace_id, filter_obj, &columns, now),
        "peer_reputation" => query_generic_scan(ctx, &query_id, "peer_reputation", workspace_id, filter_obj, &columns, now),
        "memory_revision" => query_memory_revision(ctx, query_id, workspace_id, filter_obj, &columns, now),
        "note_revision" => query_note_revision(ctx, query_id, workspace_id, filter_obj, &columns, now),
        // SDK-internal result tables (used by _query)
        "search_index" => query_search_index(ctx, &query_id, workspace_id, filter_obj, &columns, now),
        "hybrid_result" => query_hybrid_result(ctx, &query_id, workspace_id, filter_obj, &columns, now),
        "entity_extraction_result" => query_entity_extraction_result(ctx, &query_id, workspace_id, filter_obj, &columns, now),
        "user_memory_result" => query_user_memory_result(ctx, &query_id, workspace_id, filter_obj, &columns, now),
        // Graph result tables (private, read via _query). These previously fell
        // through to the query_generic no-op stub, silently returning empty —
        // SDK compute_kg_stats / detect_bridge_nodes / graph_bfs / shortest_path
        // returned None/[] even after a successful reducer. Fixed 2026-08-02.
        "kg_stats_result" => query_kg_stats_result(ctx, &query_id, workspace_id, filter_obj, &columns, now),
        "bridge_result" => query_bridge_result(ctx, &query_id, workspace_id, filter_obj, &columns, now),
        "graph_traversal_result" => query_graph_traversal_result(ctx, &query_id, workspace_id, filter_obj, &columns, now),
        "shortest_path_result" => query_shortest_path_result(ctx, &query_id, workspace_id, filter_obj, &columns, now),
        "memory_recommendation" => query_memory_recommendation(ctx, &query_id, workspace_id, filter_obj, &columns, now),
        _ => query_generic(ctx, &query_id, &table_name, workspace_id, filter_obj, &columns, now),
    }
}

// ── Per-table query helpers ────────────────────────────────────────────

fn insert_row(ctx: &ReducerContext, query_id: &str, table_name: &str, row_json: String, now: i64) {
    // uuid_v7(ctx) alone is NOT collision-safe within a single reducer
    // transaction: STDB's new_uuid_v7() can return the same value for
    // successive calls in the same batch, which made query_table panic with
    // "duplicate unique column" on query_result when a query returned
    // multiple rows. Retry against the table until a fresh id is found.
    let id = uuid_v7_uniq(ctx, |candidate: &String| {
        ctx.db.query_result().id().find(candidate).is_none()
    }, 32);
    ctx.db.query_result().insert(GenericQueryResult {
        id,
        query_id: query_id.to_string(),
        table_name: table_name.to_string(),
        row_json,
        created_at: now,
    });
}

fn row_to_json(row: &serde_json::Value, columns: &[String]) -> String {
    if columns.is_empty() {
        serde_json::to_string(row).unwrap_or_else(|_| "{}".to_string())
    } else if let Some(obj) = row.as_object() {
        let filtered: serde_json::Map<String, serde_json::Value> = obj.iter()
            .filter(|(k, _)| columns.contains(k))
            .map(|(k, v)| (k.clone(), v.clone()))
            .collect();
        serde_json::to_string(&filtered).unwrap_or_else(|_| "{}".to_string())
    } else {
        serde_json::to_string(row).unwrap_or_else(|_| "{}".to_string())
    }
}

fn filter_matches(row: &serde_json::Value, filter: &serde_json::Map<String, serde_json::Value>) -> bool {
    let obj = match row.as_object() {
        Some(o) => o,
        None => return false,
    };
    for (key, expected) in filter {
        let actual = match obj.get(key) {
            Some(v) => v,
            None => return false,
        };
        // String equality for simple filters; JSON match for complex
        if expected.is_string() && actual.is_string() {
            if expected.as_str() != actual.as_str() {
                return false;
            }
        } else if expected.is_boolean() && actual.is_boolean() {
            if expected.as_bool() != actual.as_bool() {
                return false;
            }
        } else if expected.is_number() && actual.is_number() {
            // Compare as f64 for simplicity
            let e = expected.as_f64().unwrap_or(0.0);
            let a = actual.as_f64().unwrap_or(0.0);
            if (e - a).abs() > f64::EPSILON {
                return false;
            }
        // Coerce string to boolean for SDK convenience (list_memories sends "true"/"false")
        } else if expected.is_string() && actual.is_boolean() {
            let expected_bool = expected.as_str().map(|s| s.eq_ignore_ascii_case("true")).unwrap_or(false);
            if expected_bool != actual.as_bool().unwrap_or(false) {
                return false;
            }
        // Coerce string to number for SDK convenience
        } else if expected.is_string() && actual.is_number() {
            let expected_num: f64 = match expected.as_str().and_then(|s| s.parse().ok()) {
                Some(n) => n,
                None => return false,
            };
            let actual_num = actual.as_f64().unwrap_or(0.0);
            if (expected_num - actual_num).abs() > f64::EPSILON {
                return false;
            }
        } else if expected != actual {
            return false;
        }
    }
    true
}

// ── Table-specific query implementations ───────────────────────────────

fn query_memory(
    ctx: &ReducerContext, query_id: String, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    // NB: .take() AFTER .filter() so workspaces past row 1000 are not
    // silently excluded. Use a bigger cap when targeting a workspace.
    let max_desired = if workspace_id.is_empty() { crate::MAX_RESULTS } else { crate::MAX_RESULTS * 10 };
    if workspace_id.is_empty() {
        for m in ctx.db.memory().iter().filter(|m: &crate::memory::Memory| m.is_active).take(max_desired) {
            let row = serde_json::json!({
                "id": m.id, "workspace_id": m.workspace_id, "content": m.content,
                "summary": m.summary, "memory_type": m.memory_type,
                "peer_id": m.peer_id, "observer_id": m.observer_id,
                "source_session_id": m.source_session_id, "source_message_id": m.source_message_id,
                "entities_json": m.entities_json, "confidence": m.confidence,
                "context": m.context,
                "tier": m.tier, "is_active": m.is_active,
                "expires_at": m.expires_at,
                "created_at": m.created_at, "updated_at": m.updated_at,
                "access_count": m.access_count, "strength": m.strength, "version": m.version,
                "valid_from": m.valid_from, "valid_to": m.valid_to,
                "parent_directory_id": m.parent_directory_id,
                "consolidated_to": m.consolidated_to,
                "trust_score": m.trust_score, "feedback_count": m.feedback_count,
                "user_scope": m.user_scope,
                "source_url": m.source_url.clone().unwrap_or_default(),
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "memory", row_to_json(&row, columns), now);
            }
        }
    } else {
        for m in ctx.db.memory().workspace_id().filter(&workspace_id).filter(|m: &crate::memory::Memory| m.is_active).take(max_desired) {
            let row = serde_json::json!({
                "id": m.id, "workspace_id": m.workspace_id, "content": m.content,
                "summary": m.summary, "memory_type": m.memory_type,
                "peer_id": m.peer_id, "observer_id": m.observer_id,
                "source_session_id": m.source_session_id, "source_message_id": m.source_message_id,
                "entities_json": m.entities_json, "confidence": m.confidence,
                "context": m.context,
                "tier": m.tier, "is_active": m.is_active,
                "expires_at": m.expires_at,
                "created_at": m.created_at, "updated_at": m.updated_at,
                "access_count": m.access_count, "strength": m.strength, "version": m.version,
                "valid_from": m.valid_from, "valid_to": m.valid_to,
                "parent_directory_id": m.parent_directory_id,
                "consolidated_to": m.consolidated_to,
                "trust_score": m.trust_score, "feedback_count": m.feedback_count,
                "user_scope": m.user_scope,
                "source_url": m.source_url.clone().unwrap_or_default(),
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "memory", row_to_json(&row, columns), now);
            }
        }
    }
    Ok(())
}

fn query_kg_node(
    ctx: &ReducerContext, query_id: String, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    if workspace_id.is_empty() {
        for n in ctx.db.kg_node().iter().take(crate::MAX_RESULTS) {
        let row = serde_json::json!({
            "id": n.id, "workspace_id": n.workspace_id, "label": n.label,
            "node_type": n.node_type, "metadata_json": n.metadata_json,
            "summary": n.summary, "community_id": n.community_id,
            "embedding_json": n.embedding_json,
            "source_memory_id": n.source_memory_id,
            "source_document_id": n.source_document_id,
            "stale_since": n.stale_since,
            "created_at": n.created_at,
        });
        if filter_matches(&row, filter) {
            insert_row(ctx, &query_id, "kg_node", row_to_json(&row, columns), now);
        }
    }
    } else {
        for n in ctx.db.kg_node().workspace_id().filter(&workspace_id).take(crate::MAX_RESULTS) {
        let row = serde_json::json!({
            "id": n.id, "workspace_id": n.workspace_id, "label": n.label,
            "node_type": n.node_type, "metadata_json": n.metadata_json,
            "summary": n.summary, "community_id": n.community_id,
            "embedding_json": n.embedding_json,
            "source_memory_id": n.source_memory_id,
            "source_document_id": n.source_document_id,
            "stale_since": n.stale_since,
            "created_at": n.created_at,
        });
        if filter_matches(&row, filter) {
            insert_row(ctx, &query_id, "kg_node", row_to_json(&row, columns), now);
        }
    }
    }
    Ok(())
}

fn query_kg_edge(
    ctx: &ReducerContext, query_id: String, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    if workspace_id.is_empty() {
        for e in ctx.db.kg_edge().iter().take(crate::MAX_RESULTS) {
        let row = serde_json::json!({
            "id": e.id, "workspace_id": e.workspace_id,
            "source_node_id": e.source_node_id, "target_node_id": e.target_node_id,
            "relation": e.relation, "weight": e.weight,
            "confidence": e.confidence, "metadata_json": e.metadata_json,
            "edge_group_id": e.edge_group_id,
            "version": e.version, "valid_at": e.valid_at, "invalid_at": e.invalid_at,
            "created_at": e.created_at,
            "source_memory_id": e.source_memory_id,
        });
        if filter_matches(&row, filter) {
            insert_row(ctx, &query_id, "kg_edge", row_to_json(&row, columns), now);
        }
    }
    } else {
        for e in ctx.db.kg_edge().workspace_id().filter(&workspace_id).take(crate::MAX_RESULTS) {
        let row = serde_json::json!({
            "id": e.id, "workspace_id": e.workspace_id,
            "source_node_id": e.source_node_id, "target_node_id": e.target_node_id,
            "relation": e.relation, "weight": e.weight,
            "confidence": e.confidence, "metadata_json": e.metadata_json,
            "edge_group_id": e.edge_group_id,
            "version": e.version, "valid_at": e.valid_at, "invalid_at": e.invalid_at,
            "created_at": e.created_at,
            "source_memory_id": e.source_memory_id,
        });
        if filter_matches(&row, filter) {
            insert_row(ctx, &query_id, "kg_edge", row_to_json(&row, columns), now);
        }
    }
    }
    Ok(())
}

fn query_kg_community(
    ctx: &ReducerContext, query_id: String, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    if workspace_id.is_empty() {
        for c in ctx.db.kg_community().iter().take(crate::MAX_RESULTS) {
            let row = serde_json::json!({
                "id": c.id, "workspace_id": c.workspace_id,
                "name": c.name, "summary": c.summary,
                "created_at": c.created_at,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "kg_community", row_to_json(&row, columns), now);
            }
        }
    } else {
        for c in ctx.db.kg_community().workspace_id().filter(&workspace_id).take(crate::MAX_RESULTS) {
            let row = serde_json::json!({
                "id": c.id, "workspace_id": c.workspace_id,
                "name": c.name, "summary": c.summary,
                "created_at": c.created_at,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "kg_community", row_to_json(&row, columns), now);
            }
        }
    }
    Ok(())
}

fn query_session(
    ctx: &ReducerContext, query_id: String, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    if workspace_id.is_empty() {
        for s in ctx.db.session().iter().take(crate::MAX_RESULTS) {
            let row = serde_json::json!({
                "id": s.id, "workspace_id": s.workspace_id, "name": s.name,
                "summary": s.summary, "metadata": s.metadata,
                "created_at": s.created_at, "updated_at": s.updated_at,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "session", row_to_json(&row, columns), now);
            }
        }
    } else {
        for s in ctx.db.session().workspace_id().filter(&workspace_id)
            .take(crate::MAX_RESULTS) {
            let row = serde_json::json!({
                "id": s.id, "workspace_id": s.workspace_id, "name": s.name,
                "summary": s.summary, "metadata": s.metadata,
                "created_at": s.created_at, "updated_at": s.updated_at,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "session", row_to_json(&row, columns), now);
            }
        }
    }
    Ok(())
}

fn query_message(
    ctx: &ReducerContext, query_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    for msg in ctx.db.message().iter().take(crate::MAX_RESULTS) {
        let row = serde_json::json!({
            "id": msg.id, "session_id": msg.session_id,
            "sender_id": msg.sender_id, "content": msg.content,
            "content_type": msg.content_type, "metadata": msg.metadata,
            "created_at": msg.created_at,
        });
        if filter_matches(&row, filter) {
            insert_row(ctx, &query_id, "message", row_to_json(&row, columns), now);
        }
    }
    Ok(())
}

fn query_note(
    ctx: &ReducerContext, query_id: String, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    if workspace_id.is_empty() {
        for n in ctx.db.note().iter().filter(|n: &crate::note::Note| n.is_active).take(crate::MAX_RESULTS) {
        let row = serde_json::json!({
            "id": n.id, "workspace_id": n.workspace_id,
            "title": n.title, "content": n.content,
            "note_date": n.note_date,
            "embedding_json": n.embedding_json,
            "backlink_count": n.backlink_count, "block_ref_count": n.block_ref_count,
            "is_active": n.is_active,
            "created_at": n.created_at, "updated_at": n.updated_at,
        });
        if filter_matches(&row, filter) {
            insert_row(ctx, &query_id, "note", row_to_json(&row, columns), now);
        }
    }
    } else {
        for n in ctx.db.note().workspace_id().filter(&workspace_id).filter(|n: &crate::note::Note| n.is_active).take(crate::MAX_RESULTS) {
        let row = serde_json::json!({
            "id": n.id, "workspace_id": n.workspace_id,
            "title": n.title, "content": n.content,
            "note_date": n.note_date,
            "embedding_json": n.embedding_json,
            "backlink_count": n.backlink_count, "block_ref_count": n.block_ref_count,
            "is_active": n.is_active,
            "created_at": n.created_at, "updated_at": n.updated_at,
        });
        if filter_matches(&row, filter) {
            insert_row(ctx, &query_id, "note", row_to_json(&row, columns), now);
        }
    }
    }
    Ok(())
}

fn query_note_backlink(
    ctx: &ReducerContext, query_id: String, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    if workspace_id.is_empty() {
        for nb in ctx.db.note_backlink().iter().take(crate::MAX_RESULTS) {
            let source_note = ctx.db.note().id().find(&nb.source_note_id);
            let source_title = source_note.map(|n: crate::note::Note| n.title).unwrap_or_default();
            let target_title = ctx.db.note().id().find(&nb.target_note_id)
                .map(|n: crate::note::Note| n.title)
                .unwrap_or_default();
            let row = serde_json::json!({
                "id": nb.id,
                "source_note_id": nb.source_note_id, "target_note_id": nb.target_note_id,
                "display_text": nb.display_text,
                "source_title": source_title, "target_title": target_title,
                "created_at": nb.created_at,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "note_backlink", row_to_json(&row, columns), now);
            }
        }
    } else {
        for nb in ctx.db.note_backlink().workspace_id().filter(&workspace_id).take(crate::MAX_RESULTS) {
            let source_note = ctx.db.note().id().find(&nb.source_note_id);
            let source_title = source_note.map(|n: crate::note::Note| n.title).unwrap_or_default();
            let target_title = ctx.db.note().id().find(&nb.target_note_id)
                .map(|n: crate::note::Note| n.title)
                .unwrap_or_default();
            let row = serde_json::json!({
                "id": nb.id,
                "source_note_id": nb.source_note_id, "target_note_id": nb.target_note_id,
                "display_text": nb.display_text,
                "source_title": source_title, "target_title": target_title,
                "created_at": nb.created_at,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "note_backlink", row_to_json(&row, columns), now);
            }
        }
    }
    Ok(())
}

fn query_profile(
    ctx: &ReducerContext, query_id: String, _workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    for p in ctx.db.profile().iter().take(crate::MAX_RESULTS) {
        let row = serde_json::json!({
            "id": p.id,
            "peer_id": p.peer_id,
            "static_facts_json": p.static_facts_json,
            "dynamic_context_json": p.dynamic_context_json,
            "preferences_json": p.preferences_json,
            "tags_json": p.tags_json,
            "updated_at": p.updated_at,
        });
        if filter_matches(&row, filter) {
            insert_row(ctx, &query_id, "profile", row_to_json(&row, columns), now);
        }
    }
    Ok(())
}

fn query_peer(
    ctx: &ReducerContext, query_id: String, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    if workspace_id.is_empty() {
        for p in ctx.db.peer().iter().take(crate::MAX_RESULTS) {
            let row = serde_json::json!({
                "id": p.id, "workspace_id": p.workspace_id,
                "name": p.name, "peer_type": p.peer_type,
                "metadata": p.metadata,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "peer", row_to_json(&row, columns), now);
            }
        }
    } else {
        for p in ctx.db.peer().workspace_id().filter(&workspace_id)
            .take(crate::MAX_RESULTS) {
            let row = serde_json::json!({
                "id": p.id, "workspace_id": p.workspace_id,
                "name": p.name, "peer_type": p.peer_type,
                "metadata": p.metadata,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "peer", row_to_json(&row, columns), now);
            }
        }
    }
    Ok(())
}

fn query_workspace(
    ctx: &ReducerContext, query_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    for ws in ctx.db.workspace().iter().take(crate::MAX_RESULTS) {
        let row = serde_json::json!({
            "id": ws.id, "name": ws.name, "description": ws.description,
            "created_at": ws.created_at, "updated_at": ws.updated_at,
            "is_public": ws.is_public,
        });
        if filter_matches(&row, filter) {
            insert_row(ctx, &query_id, "workspace", row_to_json(&row, columns), now);
        }
    }
    Ok(())
}

fn query_agent_step(
    ctx: &ReducerContext, query_id: String, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    if workspace_id.is_empty() {
        for step in ctx.db.agent_step().iter().take(crate::MAX_RESULTS) {
            let row = serde_json::json!({
                "id": step.id, "session_id": step.session_id,
                "workspace_id": step.workspace_id,
                "step_type": step.step_type, "content": step.content,
                "summary": step.summary, "parent_step_id": step.parent_step_id,
                "created_at": step.created_at,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "agent_step", row_to_json(&row, columns), now);
            }
        }
    } else {
        for step in ctx.db.agent_step().workspace_id().filter(&workspace_id).take(crate::MAX_RESULTS) {
            let row = serde_json::json!({
                "id": step.id, "session_id": step.session_id,
                "workspace_id": step.workspace_id,
                "step_type": step.step_type, "content": step.content,
                "summary": step.summary, "parent_step_id": step.parent_step_id,
                "created_at": step.created_at,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "agent_step", row_to_json(&row, columns), now);
            }
        }
    }
    Ok(())
}

fn query_context_pack(
    ctx: &ReducerContext, query_id: String, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    if workspace_id.is_empty() {
        for cp in ctx.db.context_pack().iter().take(crate::MAX_RESULTS) {
            let row = serde_json::json!({
                "id": cp.id, "workspace_id": cp.workspace_id,
                "query_hash": cp.query_hash, "pack_json": cp.pack_json,
                "token_count": cp.token_count,
                "created_at": cp.created_at,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "context_pack", row_to_json(&row, columns), now);
            }
        }
    } else {
        for cp in ctx.db.context_pack().workspace_id().filter(&workspace_id).take(crate::MAX_RESULTS) {
            let row = serde_json::json!({
                "id": cp.id, "workspace_id": cp.workspace_id,
                "query_hash": cp.query_hash, "pack_json": cp.pack_json,
                "token_count": cp.token_count,
                "created_at": cp.created_at,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "context_pack", row_to_json(&row, columns), now);
            }
        }
    }
    Ok(())
}

fn query_connector_config(
    ctx: &ReducerContext, query_id: String, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    if workspace_id.is_empty() {
        for cc in ctx.db.connector_config().iter().take(crate::MAX_RESULTS) {
            let row = serde_json::json!({
                "id": cc.id, "name": cc.name, "connector_type": cc.connector_type,
                "config_json": cc.config_json, "workspace_id": cc.workspace_id,
                "schedule_secs": cc.schedule_secs, "is_active": cc.is_active,
                "created_at": cc.created_at, "updated_at": cc.updated_at,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "connector_config", row_to_json(&row, columns), now);
            }
        }
    } else {
        for cc in ctx.db.connector_config().workspace_id().filter(&workspace_id).take(crate::MAX_RESULTS) {
            let row = serde_json::json!({
                "id": cc.id, "name": cc.name, "connector_type": cc.connector_type,
                "config_json": cc.config_json, "workspace_id": cc.workspace_id,
                "schedule_secs": cc.schedule_secs, "is_active": cc.is_active,
                "created_at": cc.created_at, "updated_at": cc.updated_at,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "connector_config", row_to_json(&row, columns), now);
            }
        }
    }
    Ok(())
}

/// Query memory revision history by memory_id.
fn query_memory_revision(
    ctx: &ReducerContext, query_id: String, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    if workspace_id.is_empty() {
        for rev in ctx.db.memory_revision().iter().take(crate::MAX_RESULTS) {
            let row = serde_json::json!({
                "id": rev.id, "memory_id": rev.memory_id, "workspace_id": rev.workspace_id,
                "version": rev.version,
                "previous_content": rev.previous_content, "previous_summary": rev.previous_summary,
                "previous_confidence": rev.previous_confidence,
                "new_content": rev.new_content, "new_summary": rev.new_summary,
                "new_confidence": rev.new_confidence,
                "changed_at": rev.changed_at, "changed_by": rev.changed_by,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "memory_revision", row_to_json(&row, columns), now);
            }
        }
    } else {
        for rev in ctx.db.memory_revision().workspace_id().filter(&workspace_id).take(crate::MAX_RESULTS) {
            let row = serde_json::json!({
                "id": rev.id, "memory_id": rev.memory_id, "workspace_id": rev.workspace_id,
                "version": rev.version,
                "previous_content": rev.previous_content, "previous_summary": rev.previous_summary,
                "previous_confidence": rev.previous_confidence,
                "new_content": rev.new_content, "new_summary": rev.new_summary,
                "new_confidence": rev.new_confidence,
                "changed_at": rev.changed_at, "changed_by": rev.changed_by,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "memory_revision", row_to_json(&row, columns), now);
            }
        }
    }
    Ok(())
}

fn query_note_revision(
    ctx: &ReducerContext, query_id: String, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    if workspace_id.is_empty() {
        for rev in ctx.db.note_revision().iter().take(crate::MAX_RESULTS) {
            let row = serde_json::json!({
                "id": rev.id, "note_id": rev.note_id, "workspace_id": rev.workspace_id,
                "version": rev.version,
                "previous_title": rev.previous_title, "previous_content": rev.previous_content,
                "new_title": rev.new_title, "new_content": rev.new_content,
                "changed_at": rev.changed_at, "changed_by": rev.changed_by,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "note_revision", row_to_json(&row, columns), now);
            }
        }
    } else {
        for rev in ctx.db.note_revision().workspace_id().filter(&workspace_id).take(crate::MAX_RESULTS) {
            let row = serde_json::json!({
                "id": rev.id, "note_id": rev.note_id, "workspace_id": rev.workspace_id,
                "version": rev.version,
                "previous_title": rev.previous_title, "previous_content": rev.previous_content,
                "new_title": rev.new_title, "new_content": rev.new_content,
                "changed_at": rev.changed_at, "changed_by": rev.changed_by,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, &query_id, "note_revision", row_to_json(&row, columns), now);
            }
        }
    }
    Ok(())
}

/// Generic scan for tables that support simple id/workspace_id filtering.
/// Maps alias table names to their real accessors.
fn query_generic_scan(
    ctx: &ReducerContext, query_id: &str, table_name: &str, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    match table_name {
        "context_directory" => {
            if workspace_id.is_empty() {
                for row in ctx.db.context_directory().iter().take(crate::MAX_RESULTS) {
                    let val = serde_json::json!({
                        "id": row.id, "workspace_id": row.workspace_id,
                        "name": row.name, "path": row.path,
                        "parent_id": row.parent_id, "description": row.description,
                        "created_at": row.created_at, "updated_at": row.updated_at,
                    });
                    if filter_matches(&val, filter) {
                        insert_row(ctx, query_id, table_name, row_to_json(&val, columns), now);
                    }
                }
            } else {
                for row in ctx.db.context_directory().workspace_id().filter(&workspace_id).take(crate::MAX_RESULTS) {
                    let val = serde_json::json!({
                        "id": row.id, "workspace_id": row.workspace_id,
                        "name": row.name, "path": row.path,
                        "parent_id": row.parent_id, "description": row.description,
                        "created_at": row.created_at, "updated_at": row.updated_at,
                    });
                    if filter_matches(&val, filter) {
                        insert_row(ctx, query_id, table_name, row_to_json(&val, columns), now);
                    }
                }
            }
        }
        "delta_pack" => {
            if workspace_id.is_empty() {
                for row in ctx.db.delta_pack().iter().take(crate::MAX_RESULTS) {
                    let val = serde_json::json!({
                        "id": row.id, "workspace_id": row.workspace_id,
                        "previous_context_pack_id": row.previous_context_pack_id,
                        "query_hash": row.query_hash,
                        "changed_memory_ids_json": row.changed_memory_ids_json,
                        "removed_memory_ids_json": row.removed_memory_ids_json,
                        "new_memories_json": row.new_memories_json,
                        "estimated_tokens": row.estimated_tokens,
                        "created_at": row.created_at,
                    });
                    if filter_matches(&val, filter) {
                        insert_row(ctx, query_id, table_name, row_to_json(&val, columns), now);
                    }
                }
            } else {
                for row in ctx.db.delta_pack().workspace_id().filter(&workspace_id).take(crate::MAX_RESULTS) {
                    let val = serde_json::json!({
                        "id": row.id, "workspace_id": row.workspace_id,
                        "previous_context_pack_id": row.previous_context_pack_id,
                        "query_hash": row.query_hash,
                        "changed_memory_ids_json": row.changed_memory_ids_json,
                        "removed_memory_ids_json": row.removed_memory_ids_json,
                        "new_memories_json": row.new_memories_json,
                        "estimated_tokens": row.estimated_tokens,
                        "created_at": row.created_at,
                    });
                    if filter_matches(&val, filter) {
                        insert_row(ctx, query_id, table_name, row_to_json(&val, columns), now);
                    }
                }
            }
        }
        "peer_reputation" => {
            for row in ctx.db.peer_reputation().iter().take(crate::MAX_RESULTS) {
                let val = serde_json::json!({
                    "id": row.id, "helpful_count": row.helpful_count,
                    "unhelpful_count": row.unhelpful_count,
                    "total_feedback": row.total_feedback,
                    "reputation_score": row.reputation_score,
                    "last_feedback_at": row.last_feedback_at,
                });
                if filter_matches(&val, filter) {
                    insert_row(ctx, query_id, table_name, row_to_json(&val, columns), now);
                }
            }
        }
        _ => {}
    }
    Ok(())
}

/// Fallback for tables without a specialized query function.
/// Only supports simple id/workspace_id filtering.
fn query_generic(
    ctx: &ReducerContext, query_id: &str, table_name: &str, _workspace_id: String,
    _filter: &serde_json::Map<String, serde_json::Value>, _columns: &[String], now: i64,
) -> Result<(), String> {
    // Fallback for unhandled tables.
    let _ = (ctx, query_id, table_name, _workspace_id, now, _filter, _columns);
    Ok(())
}

// ── Graph result table queries ─────────────────────────────────────────
// These result tables are private; SDK code reads them through _query() →
// query_table. Earlier they fell through to the no-op query_generic stub,
// so compute_kg_stats / detect_bridge_nodes / graph_bfs / shortest_path /
// memory_recommendation all silently returned empty even after the reducer
// succeeded. Each reader mirrors the row's struct fields as JSON.

fn query_kg_stats_result(
    ctx: &ReducerContext, query_id: &str, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    for r in ctx.db.kg_stats_result().iter().take(crate::MAX_RESULTS) {
        if !workspace_id.is_empty() && r.workspace_id != workspace_id {
            continue;
        }
        let val = serde_json::json!({
            "id": r.id, "workspace_id": r.workspace_id,
            "node_count": r.node_count, "edge_count": r.edge_count,
            "community_count": r.community_count, "unassigned_nodes": r.unassigned_nodes,
            "orphan_nodes": r.orphan_nodes, "avg_degree": r.avg_degree,
            "created_at": r.created_at,
        });
        if filter_matches(&val, filter) {
            insert_row(ctx, query_id, "kg_stats_result", row_to_json(&val, columns), now);
        }
    }
    Ok(())
}

fn query_bridge_result(
    ctx: &ReducerContext, query_id: &str, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    for r in ctx.db.bridge_result().iter().take(crate::MAX_RESULTS) {
        if !workspace_id.is_empty() && r.workspace_id != workspace_id {
            continue;
        }
        let val = serde_json::json!({
            "id": r.id, "workspace_id": r.workspace_id,
            "node_id": r.node_id, "node_label": r.node_label,
            "node_type": r.node_type, "community_count": r.community_count,
            "bridge_score": r.bridge_score, "community_ids_json": r.community_ids_json,
            "created_at": r.created_at,
        });
        if filter_matches(&val, filter) {
            insert_row(ctx, query_id, "bridge_result", row_to_json(&val, columns), now);
        }
    }
    Ok(())
}

fn query_graph_traversal_result(
    ctx: &ReducerContext, query_id: &str, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    for r in ctx.db.graph_traversal_result().iter().take(crate::MAX_RESULTS) {
        if !workspace_id.is_empty() && r.workspace_id != workspace_id {
            continue;
        }
        let val = serde_json::json!({
            "id": r.id, "workspace_id": r.workspace_id, "query_id": r.query_id,
            "node_id": r.node_id, "node_label": r.node_label,
            "node_type": r.node_type, "depth": r.depth,
            "path_json": r.path_json, "created_at": r.created_at,
        });
        if filter_matches(&val, filter) {
            insert_row(ctx, query_id, "graph_traversal_result", row_to_json(&val, columns), now);
        }
    }
    Ok(())
}

fn query_shortest_path_result(
    ctx: &ReducerContext, query_id: &str, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    for r in ctx.db.shortest_path_result().iter().take(crate::MAX_RESULTS) {
        if !workspace_id.is_empty() && r.workspace_id != workspace_id {
            continue;
        }
        let val = serde_json::json!({
            "id": r.id, "workspace_id": r.workspace_id, "query_id": r.query_id,
            "step_order": r.step_order, "node_id": r.node_id,
            "node_label": r.node_label, "node_type": r.node_type,
            "created_at": r.created_at,
        });
        if filter_matches(&val, filter) {
            insert_row(ctx, query_id, "shortest_path_result", row_to_json(&val, columns), now);
        }
    }
    Ok(())
}

fn query_memory_recommendation(
    ctx: &ReducerContext, query_id: &str, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    for r in ctx.db.memory_recommendation().iter().take(crate::MAX_RESULTS) {
        if !workspace_id.is_empty() && r.workspace_id != workspace_id {
            continue;
        }
        let val = serde_json::json!({
            "id": r.id, "workspace_id": r.workspace_id, "memory_id": r.memory_id,
            "content": r.content, "trust_score": r.trust_score,
            "feedback_count": r.feedback_count, "action": r.action,
            "urgency": r.urgency, "created_at": r.created_at,
        });
        if filter_matches(&val, filter) {
            insert_row(ctx, query_id, "memory_recommendation", row_to_json(&val, columns), now);
        }
    }
    Ok(())
}

fn query_search_index(
    ctx: &ReducerContext, query_id: &str, workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    if workspace_id.is_empty() {
        for si in ctx.db.search_index().iter().take(crate::MAX_RESULTS) {
            let row = serde_json::json!({
                "id": si.id, "workspace_id": si.workspace_id,
                "entity_id": si.entity_id, "entity_type": si.entity_type,
                "content": si.content, "embedding_json": si.embedding_json,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, query_id, "search_index", row_to_json(&row, columns), now);
            }
        }
    } else {
        for si in ctx.db.search_index().workspace_id().filter(&workspace_id).take(crate::MAX_RESULTS * 10) {
            let row = serde_json::json!({
                "id": si.id, "workspace_id": si.workspace_id,
                "entity_id": si.entity_id, "entity_type": si.entity_type,
                "content": si.content, "embedding_json": si.embedding_json,
            });
            if filter_matches(&row, filter) {
                insert_row(ctx, query_id, "search_index", row_to_json(&row, columns), now);
            }
        }
    }
    Ok(())
}

fn query_hybrid_result(
    ctx: &ReducerContext, query_id: &str, _workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    for hr in ctx.db.hybrid_result().iter().take(crate::MAX_RESULTS) {
        let row = serde_json::json!({
            "id": hr.id, "workspace_id": hr.workspace_id,
            "query_hash": hr.query_hash, "entity_id": hr.entity_id,
            "entity_type": hr.entity_type, "content": hr.content,
            "score": hr.score, "strategy": hr.strategy,
        });
        if filter_matches(&row, filter) {
            insert_row(ctx, query_id, "hybrid_result", row_to_json(&row, columns), now);
        }
    }
    Ok(())
}

fn query_entity_extraction_result(
    ctx: &ReducerContext, query_id: &str, _workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    for e in ctx.db.entity_extraction_result().iter().take(crate::MAX_RESULTS) {
        let row = serde_json::json!({
            "id": e.id,
            "workspace_id": e.workspace_id,
            "entities_json": e.entities_json,
            "kg_node_count": e.kg_node_count,
            "edge_count": e.edge_count,
        });
        if filter_matches(&row, filter) {
            insert_row(ctx, query_id, "entity_extraction_result", row_to_json(&row, columns), now);
        }
    }
    Ok(())
}

fn query_user_memory_result(
    ctx: &ReducerContext, query_id: &str, _workspace_id: String,
    filter: &serde_json::Map<String, serde_json::Value>, columns: &[String], now: i64,
) -> Result<(), String> {
    for u in ctx.db.user_memory_result().iter().take(crate::MAX_RESULTS) {
        let row = serde_json::json!({
            "id": u.id, "user_scope": u.user_scope,
            "memory_id": u.memory_id, "workspace_id": u.workspace_id,
        });
        if filter_matches(&row, filter) {
            insert_row(ctx, query_id, "user_memory_result", row_to_json(&row, columns), now);
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_row_to_json_all_columns() {
        let row = serde_json::json!({"id": "abc", "content": "hello", "score": 0.95});
        let result = row_to_json(&row, &[]);
        // All columns — should contain all three keys
        assert!(result.contains("id"));
        assert!(result.contains("content"));
        assert!(result.contains("score"));
    }

    #[test]
    fn test_row_to_json_filtered() {
        let row = serde_json::json!({"id": "abc", "content": "hello", "score": 0.95});
        let result = row_to_json(
            &row,
            &["id".to_string(), "score".to_string()],
        );
        assert!(result.contains("id"));
        assert!(result.contains("score"));
        assert!(!result.contains("content"));
    }

    #[test]
    fn test_filter_matches_string_match() {
        let row = serde_json::json!({"id": "abc", "type": "memory"});
        let mut filter = serde_json::Map::new();
        filter.insert("type".to_string(), serde_json::Value::String("memory".to_string()));
        assert!(filter_matches(&row, &filter));
    }

    #[test]
    fn test_filter_matches_string_mismatch() {
        let row = serde_json::json!({"id": "abc", "type": "memory"});
        let mut filter = serde_json::Map::new();
        filter.insert("type".to_string(), serde_json::Value::String("fact".to_string()));
        assert!(!filter_matches(&row, &filter));
    }

    #[test]
    fn test_filter_matches_missing_key() {
        let row = serde_json::json!({"id": "abc"});
        let mut filter = serde_json::Map::new();
        filter.insert("nonexistent".to_string(), serde_json::Value::String("x".to_string()));
        assert!(!filter_matches(&row, &filter));
    }

    #[test]
    fn test_filter_matches_boolean() {
        let row = serde_json::json!({"active": true});
        let mut filter = serde_json::Map::new();
        filter.insert("active".to_string(), serde_json::Value::Bool(true));
        assert!(filter_matches(&row, &filter));
    }

    #[test]
    fn test_filter_matches_number() {
        let row = serde_json::json!({"score": 0.95});
        let mut filter = serde_json::Map::new();
        filter.insert("score".to_string(), serde_json::json!(0.95));
        assert!(filter_matches(&row, &filter));
    }

    #[test]
    fn test_filter_matches_non_object() {
        let row = serde_json::json!("not an object");
        let filter = serde_json::Map::new();
        assert!(!filter_matches(&row, &filter));
    }


    // ── Edge case tests ──────────────────────────────────────────────

    #[test]
    fn test_filter_matches_special_characters() {
        let row = serde_json::json!({"id": "test@#$%^&*()", "type": "memory!@#", "content": "hello <world> & more"});
        let mut filter = serde_json::Map::new();
        filter.insert("id".to_string(), serde_json::Value::String("test@#$%^&*()".to_string()));
        assert!(filter_matches(&row, &filter));

        let mut filter2 = serde_json::Map::new();
        filter2.insert("type".to_string(), serde_json::Value::String("memory!@#".to_string()));
        assert!(filter_matches(&row, &filter2));
    }

    #[test]
    fn test_filter_matches_unicode() {
        let row = serde_json::json!({"id": "测试", "type": "mémoire", "content": "日本語の文章"});
        let mut filter = serde_json::Map::new();
        filter.insert("id".to_string(), serde_json::Value::String("测试".to_string()));
        assert!(filter_matches(&row, &filter));

        let mut filter2 = serde_json::Map::new();
        filter2.insert("type".to_string(), serde_json::Value::String("mémoire".to_string()));
        assert!(filter_matches(&row, &filter2));
    }

    #[test]
    fn test_filter_matches_empty_search() {
        let row = serde_json::json!({"id": "", "type": "", "content": "hello"});
        let mut filter = serde_json::Map::new();
        filter.insert("id".to_string(), serde_json::Value::String("".to_string()));
        assert!(filter_matches(&row, &filter));

        let mut filter2 = serde_json::Map::new();
        filter2.insert("type".to_string(), serde_json::Value::String("".to_string()));
        assert!(filter_matches(&row, &filter2));
    }

    #[test]
    fn test_filter_matches_very_large_content() {
        // Create a large value (>10KB)
        let large = "x".repeat(10_000);
        let row = serde_json::json!({"id": "large", "content": large});
        let mut filter = serde_json::Map::new();
        filter.insert("content".to_string(), serde_json::Value::String(large.clone()));
        assert!(filter_matches(&row, &filter));

        // Partial match of large content (exact only, filter_matches is not substring)
        let mut filter2 = serde_json::Map::new();
        filter2.insert("id".to_string(), serde_json::Value::String("large".to_string()));
        assert!(filter_matches(&row, &filter2));
    }

    #[test]
    fn test_row_to_json_special_characters() {
        let row = serde_json::json!({"id": "test\nwith	\"quotes\"", "data": "line1\nline2"});
        let result = row_to_json(&row, &["id".to_string(), "data".to_string()]);
        assert!(result.contains("test"));
        assert!(result.contains("quotes"));
    }

    #[test]
    fn test_row_to_json_unicode() {
        let row = serde_json::json!({"id": "中文标识", "label": "étiquète"});
        let result = row_to_json(&row, &["id".to_string(), "label".to_string()]);
        assert!(result.contains("中文标识"));
        assert!(result.contains("étiquète"));
    }

    #[test]
    fn test_row_to_json_empty_response() {
        let row = serde_json::json!({"id": "", "data": ""});
        let result = row_to_json(&row, &["id".to_string(), "data".to_string()]);
        assert!(result.contains("id"));
        assert!(result.contains("data"));
    }

}
