"""Parity adapters — drop-in API compatibility with popular memory backends.

These modules provide API-compatible interfaces so apps written against
Mem0, Zep, Graphiti, Honcho, LangChain, LangMem, Cognee, Letta, QMD,
Mnemosyne, or Hindsight can use spacetime-memory as a backend without
changing their code.

This is distinct from ``spacetime_memory.connectors``, which provides
**sync connectors** that actively poll external data sources (Discord,
GitHub, RSS, etc.) and persist events as memories or KG nodes.
"""

from .graphiti import (
    AddEpisodeResults,
    AddTripletResults,
    CommunityEdge,
    CommunityNode,
    EntityEdge,
    EntityNode,
    EpisodicNode,
    Graphiti,
    SearchResults,
)
from .hindsight import (
    BankProfileResponse,
    DispositionTraits,
    FileRetainResponse,
    Hindsight,
    ListMemoryUnitsResponse,
    RecallResponse,
    RecallResult,
    ReflectFact,
    ReflectResponse,
    RetainResponse,
    TokenUsage,
)
from .honcho import Honcho, Message, Peer, Session, SyncPage
from .langchain import StmemMemoryStore, StmemStore
from .langmem import (
    ExtractedMemory,
    MemoryPhase,
    Prompt,
    ReflectionExecutor,
    create_manage_memory_tool,
    create_memory_manager,
    create_memory_searcher,
    create_memory_store_manager,
    create_multi_prompt_optimizer,
    create_prompt_optimizer,
    create_search_memory_tool,
    create_thread_extractor,
)
from .cognee import (
    MEMORY_ENTRY_TYPES,
    MemoryEntry,
    QAEntry,
    RecallScope,
    SearchResult,
    SearchResultDataset,
    SearchType,
    TraceEntry,
    FeedbackEntry,
    SkillRunEntry,
    add,
    agent_memory,
    cognify,
    config,
    datasets,
    delete,
    get_current_agent_memory_context,
    prune,
    search,
)
from .letta import (
    Block,
    CORE_MEMORY_BLOCK_CHAR_LIMIT,
    LettaMemory,
    Memory,
    Message,
    Passage,
)
from .qmd import Document, QmdClient, Query, SearchResult as QmdSearchResult, SubQuery
from .mnemosyne import (
    GRADE_FORGOTTEN_MAX,
    SM2_FIRST_INTERVAL_DAYS,
    SM2_MIN_EASINESS,
    SM2_SECOND_INTERVAL_DAYS,
    Mnemosyne,
)
from .mem0 import Memory as Mem0Memory
from .zep import (
    ApiError,
    AsyncZep,
    AsyncZepClient,
    BadRequestError,
    ConflictError,
    Fact,
    FactRatingExamples,
    FactRatingInstruction,
    Memory,
    MemoryMessage,
    MemorySearchResult,
    NotFoundError,
    RoleType,
    SearchScope,
    SearchType,
    SessionFactRatingExamples,
    SessionFactRatingInstruction,
    SuccessResponse,
    Summary,
    UserClient,
    Zep,
    ZepClient,
    ZepEnvironment,
)
from .zep import (
    Session as ZepSession,
)

__all__ = [
    "AddEpisodeResults",
    "AddTripletResults",
    "ApiError",
    "AsyncZep",
    "AsyncZepClient",
    "BadRequestError",
    "BankProfileResponse",
    "Block",
    "CORE_MEMORY_BLOCK_CHAR_LIMIT",
    "CommunityEdge",
    "CommunityNode",
    "ConflictError",
    "DispositionTraits",
    "Document",
    "EntityEdge",
    "EntityNode",
    "EpisodicNode",
    "ExtractedMemory",
    "Fact",
    "FactRatingExamples",
    "FactRatingInstruction",
    "FeedbackEntry",
    "FileRetainResponse",
    "GRADE_FORGOTTEN_MAX",
    "Graphiti",
    "Hindsight",
    "Honcho",
    "LettaMemory",
    "ListMemoryUnitsResponse",
    "MEMORY_ENTRY_TYPES",
    "Mem0Memory",
    "Memory",
    "MemoryEntry",
    "MemoryMessage",
    "MemoryPhase",
    "MemorySearchResult",
    "Message",
    "Mnemosyne",
    "NotFoundError",
    "Passage",
    "Peer",
    "Prompt",
    "QAEntry",
    "QmdClient",
    "QmdSearchResult",
    "Query",
    "RecallResponse",
    "RecallResult",
    "RecallScope",
    "ReflectionExecutor",
    "ReflectFact",
    "ReflectResponse",
    "RetainResponse",
    "RoleType",
    "SM2_FIRST_INTERVAL_DAYS",
    "SM2_MIN_EASINESS",
    "SM2_SECOND_INTERVAL_DAYS",
    "SearchResults",
    "SearchResult",
    "SearchResultDataset",
    "SearchScope",
    "SearchType",
    "Session",
    "SessionFactRatingExamples",
    "SessionFactRatingInstruction",
    "SkillRunEntry",
    "StmemMemoryStore",
    "StmemStore",
    "SubQuery",
    "SuccessResponse",
    "Summary",
    "SyncPage",
    "TokenUsage",
    "TraceEntry",
    "UserClient",
    "Zep",
    "ZepClient",
    "ZepEnvironment",
    "ZepSession",
    "add",
    "agent_memory",
    "cognify",
    "config",
    "create_manage_memory_tool",
    "create_memory_manager",
    "create_memory_searcher",
    "create_memory_store_manager",
    "create_multi_prompt_optimizer",
    "create_prompt_optimizer",
    "create_search_memory_tool",
    "create_thread_extractor",
    "datasets",
    "delete",
    "get_current_agent_memory_context",
    "prune",
    "search",
]
