"""Dreaming / Synthetic Memory module — Letta parity.

Dreaming generates synthetic memories from patterns in existing memories,
creating connections, filling gaps, and generating insights without external
input.  All computation is client-side using existing memories — no new
SpacetimeDB reducers are needed.

Reference: https://memgpt.readthedocs.io/en/latest/dreaming
"""
from __future__ import annotations

import json
import math
import time
from typing import Any

from ._base import logger
from ._search_helpers import cosine_similarity, tokenize_query

# ── Constants ───────────────────────────────────────────────────────────────

DREAM_LOG_MEMORY_TYPE = "dream_log"
"""SpacetimeDB ``memory_type`` used for dream/synthesis session records."""

SYNTHETIC_MEMORY_TYPE = "synthetic"
"""Memory type assigned to memories generated by dreaming."""

_DEFAULT_DECAY_RATE = 0.005
_DEFAULT_MAX_DAYS = 90
_DEFAULT_WEIBULL_SHAPE = 0.6
_DEFAULT_WEIBULL_SCALE = 30.0


# ── Helpers ─────────────────────────────────────────────────────────────────


def _now_seconds() -> int:
    """Return current time in seconds since epoch."""
    return int(time.time())


def _now_micros() -> int:
    """Return current time in microseconds since epoch."""
    return int(time.time() * 1_000_000)


def _weibull_decay(t_days: float, shape: float, scale: float) -> float:
    """Compute memory strength under the Weibull forgetting model.

    Args:
        t_days: Time elapsed in days since memory was encoded.
        shape: Weibull shape parameter k (k < 1 = rapid-then-slow forgetting).
        scale: Weibull scale parameter λ (characteristic time in days).

    Returns:
        Memory strength in [0.0, 1.0].
    """
    if t_days <= 0:
        return 1.0
    return math.exp(-((t_days / scale) ** shape))


def _linear_decay(t_days: float, decay_rate: float, max_days: int) -> float:
    """Compute memory strength under the linear forgetting model.

    Args:
        t_days: Time elapsed in days since memory was encoded.
        decay_rate: Fraction of strength to lose per day.
        max_days: Max age before strength hits zero.

    Returns:
        Memory strength in [0.0, 1.0].
    """
    if t_days <= 0:
        return 1.0
    strength = 1.0 - decay_rate * t_days
    return max(0.0, strength)


def _compute_memory_age_days(memory: dict[str, Any]) -> float:
    """Compute a memory's age in days using its ``created_at`` field.

    Falls back to ``updated_at`` or current time if neither is available.
    """
    now = _now_micros()
    created = memory.get("created_at", memory.get("updated_at", now))
    if isinstance(created, (int, float)) and created > 1_000_000_000_000:
        # Microseconds since epoch
        age_seconds = (now - created) / 1_000_000
    elif isinstance(created, (int, float)):
        # Seconds since epoch
        age_seconds = now / 1_000_000 - created
    else:
        age_seconds = 0.0
    return max(0.0, age_seconds / 86400.0)


def _compute_memory_strength(
    memory: dict[str, Any],
    model: str = "linear",
    decay_rate: float = _DEFAULT_DECAY_RATE,
    max_days: int = _DEFAULT_MAX_DAYS,
    weibull_shape: float = _DEFAULT_WEIBULL_SHAPE,
    weibull_scale: float = _DEFAULT_WEIBULL_SCALE,
) -> float:
    """Compute the current memory strength for a single memory.

    Args:
        memory: A memory dict (must have ``created_at`` or ``updated_at``).
        model: ``"linear"`` or ``"weibull"``.
        decay_rate: Linear decay rate.
        max_days: Linear max days.
        weibull_shape: Weibull shape parameter.
        weibull_scale: Weibull scale parameter.

    Returns:
        Strength in [0.0, 1.0].
    """
    age_days = _compute_memory_age_days(memory)
    confidence = memory.get("confidence", 0.8)
    if isinstance(confidence, str):
        try:
            confidence = float(confidence)
        except (ValueError, TypeError):
            confidence = 0.8

    if model == "weibull":
        decay = _weibull_decay(age_days, weibull_shape, weibull_scale)
    else:
        decay = _linear_decay(age_days, decay_rate, max_days)

    # Strength = confidence * time_decay
    return confidence * decay


def _extract_tokens(content: str) -> set[str]:
    """Extract meaningful tokens from memory content."""
    return set(tokenize_query(content))


def _jaccard_similarity(tokens_a: set[str], tokens_b: set[str]) -> float:
    """Compute Jaccard similarity between two token sets.

    Returns 0.0 if both sets are empty (no overlap possible).
    """
    if not tokens_a and not tokens_b:
        return 0.0
    union = tokens_a | tokens_b
    if not union:
        return 0.0
    intersection = tokens_a & tokens_b
    return len(intersection) / len(union)


# ── Dreaming Mixin ──────────────────────────────────────────────────────────


class DreamMixin:
    """Spacetime-Memory dreaming / synthetic memory mixin.

    Provides Client methods for generating synthetic memories, forgetting-curve
    analysis, memory health assessment, and scheduled dreaming cycles.

    Mnemosyne parity: forgetting-curve and decay modeling functions match the
    Mnemosyne spaced-repetition algorithm's approach to memory strength over
    time.

    Inherits from ClientBase for connection infrastructure.
    """

    # ------------------------------------------------------------------
    # 1. synthesize_memories — generate new memories from existing ones
    # ------------------------------------------------------------------

    def synthesize_memories(
        self,
        workspace_id: str,
        source_ids: list[str] | None = None,
        strategy: str = "connect",
        max_new: int = 5,
    ) -> list[dict[str, Any]]:
        """Generate new synthetic memories from existing ones.

        This is purely client-side: reads existing memories, computes
        relationships, and writes new synthetic memories via the existing
        ``store`` method.

        Args:
            workspace_id: Target workspace.
            source_ids: Optional list of specific memory IDs to use as
                source material.  If ``None``, all active memories in the
                workspace are used.
            strategy: One of ``"connect"``, ``"generalize"``, ``"fill_gaps"``,
                ``"contrast"``, or ``"all"`` (runs all applicable strategies).
            max_new: Maximum number of synthetic memories to generate.

        Returns:
            List of generated synthetic memory dicts, each with at least
            ``id``, ``content``, ``summary``, ``strategy``, and
            ``source_memory_ids``.

        Raises:
            ValueError: If *strategy* is not recognised.
        """
        valid = {"connect", "generalize", "fill_gaps", "contrast", "all"}
        if strategy not in valid:
            raise ValueError(
                f"Unknown strategy '{strategy}'. Valid options: {', '.join(sorted(valid))}"
            )

        # ── Fetch source memories ──
        if source_ids:
            memories: list[dict[str, Any]] = []
            for mid in source_ids:
                rows = self._query("memory", filter_dict={"id": mid})
                if rows:
                    memories.append(rows[0])
        else:
            memories = self._query(
                "memory",
                workspace_id=workspace_id,
                filter_dict={"workspace_id": workspace_id},
            )

        if not memories:
            logger.info("synthesize_memories: no source memories found for workspace %s", workspace_id)
            return []

        generated: list[dict[str, Any]] = []

        if strategy in ("connect", "all"):
            generated.extend(self._synthesize_connect(workspace_id, memories, max_new))
        if strategy in ("generalize", "all") and len(generated) < max_new:
            remaining = max_new - len(generated)
            generated.extend(self._synthesize_generalize(workspace_id, memories, remaining))
        if strategy in ("fill_gaps", "all") and len(generated) < max_new:
            remaining = max_new - len(generated)
            generated.extend(self._synthesize_fill_gaps(workspace_id, memories, remaining))
        if strategy in ("contrast", "all") and len(generated) < max_new:
            remaining = max_new - len(generated)
            generated.extend(self._synthesize_contrast(workspace_id, memories, remaining))

        return generated[:max_new]

    def consolidate_with_llm(
        self,
        workspace_id: str,
        source_ids: list[str],
        *,
        max_tokens: int = 1024,
        llm: Any | None = None,
    ) -> dict[str, Any]:
        """LLM-driven consolidation of similar memories (Mnemosyne parity).

        Reads the source memories, summarises them into a single
        consolidated memory via the LLM (or a grounded concatenation when
        the LLM is unavailable), then calls the ``consolidate_memories``
        reducer which deactivates the sources and records a
        ``ConsolidationLog`` entry.

        Args:
            workspace_id: Target workspace.
            source_ids: List of memory IDs to consolidate.
            max_tokens: Max tokens for the LLM summary.
            llm: Optional LLMClient-compatible object.  When omitted, the
                default LLMClient is used; if unavailable the method falls
                back to a lossless grounded concatenation.

        Returns:
            Reducer status dict with ``status``, ``consolidated_id``
            (when known), and ``source_count``.
        """
        if not source_ids:
            return {"status": "ok", "consolidated_id": "", "source_count": 0}

        memories: list[dict[str, Any]] = []
        for mid in source_ids:
            rows = self._query("memory", filter_dict={"id": mid})
            if rows:
                memories.append(rows[0])
        if not memories:
            return {"status": "ok", "consolidated_id": "", "source_count": 0}

        source_texts = []
        for m in memories:
            content = m.get("content", "")
            if content:
                source_texts.append(str(content))

        # ── LLM summary ──
        summary_text = None
        if llm is None:
            try:
                from ..llm import LLMClient

                candidate = LLMClient()
                if candidate.available:
                    llm = candidate
            except Exception:
                llm = None

        if llm is not None:
            try:
                avail = getattr(llm, "available", True)
                if not avail:
                    raise RuntimeError("llm unavailable")
                raw = llm.chat(
                    [
                        {
                            "role": "system",
                            "content": (
                                "You consolidate several memory snippets into "
                                "one concise, information-preserving summary. "
                                "Keep all durable facts, drop redundancy."
                            ),
                        },
                        {
                            "role": "user",
                            "content": (
                                "Memories:\n"
                                + "\n---\n".join(
                                    f"[{i+1}] {t[:1000]}"
                                    for i, t in enumerate(source_texts[:20])
                                )
                            ),
                        },
                    ],
                    temperature=0.0,
                    max_tokens=max_tokens,
                )
                if raw and raw.strip():
                    summary_text = raw.strip()
            except Exception:
                summary_text = None

        if not summary_text:
            # Grounded fallback (lossless): join the sources.
            summary_text = "\n".join(source_texts[:10])[:4000]

        result = self.consolidate_memories(
            workspace_id,
            source_ids,
            summary_text,
            f"Consolidated {len(source_ids)} memory/ies",
        )
        if isinstance(result, dict):
            result["source_count"] = len(source_ids)
        else:
            result = {"status": result, "source_count": len(source_ids)}
        return result

    def _synthesize_connect(
        self,
        workspace_id: str,
        memories: list[dict[str, Any]],
        max_new: int = 5,
    ) -> list[dict[str, Any]]:
        """Find related memories and create 'connection' synthetic memories.

        Uses token overlap (Jaccard + embedding cosine) to find pairs of
        memories that are related but not explicitly linked, then generates
        a synthetic memory describing the connection.
        """
        if len(memories) < 2:
            return []

        results: list[dict[str, Any]] = []
        pairs_considered = 0

        for i in range(len(memories)):
            if len(results) >= max_new:
                break
            for j in range(i + 1, len(memories)):
                if len(results) >= max_new:
                    break
                pairs_considered += 1

                m1 = memories[i]
                m2 = memories[j]

                content1 = m1.get("content", "")
                content2 = m2.get("content", "")
                if not content1 or not content2:
                    continue

                mid1 = m1.get("id", "")
                mid2 = m2.get("id", "")

                # Token-level Jaccard similarity
                tokens1 = _extract_tokens(content1)
                tokens2 = _extract_tokens(content2)
                jaccard = _jaccard_similarity(tokens1, tokens2)

                # Embedding cosine similarity if possible
                emb1 = m1.get("embedding", "")
                emb2 = m2.get("embedding", "")
                if isinstance(emb1, str) and isinstance(emb2, str):
                    from ._search_helpers import parse_embedding_json
                    vec1 = parse_embedding_json(emb1)
                    vec2 = parse_embedding_json(emb2)
                    cosine = cosine_similarity(vec1, vec2) if vec1 and vec2 else 0.0
                else:
                    cosine = 0.0

                # Combined relevance score
                if cosine > 0.0:
                    relevance = 0.4 * jaccard + 0.6 * cosine
                else:
                    relevance = jaccard  # No embeddings — use Jaccard alone

                # Threshold: moderate similarity (not too weak, not too strong)
                if 0.15 <= relevance <= 0.85:
                    connection_content = (
                        f"Connection: '{content1[:120]}…' is related to "
                        f"'{content2[:120]}…' (relevance={relevance:.2f})"
                    )
                    summary = (
                        f"Synthetic connection between related memories "
                        f"(relevance={relevance:.2f})"
                    )
                    source_ids_json = json.dumps([mid1, mid2])

                    result = self.store(
                        workspace_id=workspace_id,
                        content=connection_content,
                        summary=summary,
                        memory_type=SYNTHETIC_MEMORY_TYPE,
                        confidence=min(0.9, 0.4 + relevance * 0.5),
                        source_session_id="",
                        entities_json=source_ids_json,
                    )
                    mem_id = result.get("id", "")
                    results.append({
                        "id": mem_id,
                        "content": connection_content,
                        "summary": summary,
                        "strategy": "connect",
                        "source_memory_ids": [mid1, mid2],
                        "relevance": round(relevance, 4),
                    })

                    # Log the dream event
                    self._log_dream_event(
                        workspace_id,
                        strategy="connect",
                        generated_id=mem_id,
                        source_ids=[mid1, mid2],
                        summary=summary,
                    )

        if not results:
            logger.info(
                "_synthesize_connect: no connections found among %d memories (considered %d pairs)",
                len(memories),
                pairs_considered,
            )
        return results

    def _synthesize_generalize(
        self,
        workspace_id: str,
        memories: list[dict[str, Any]],
        max_new: int = 5,
    ) -> list[dict[str, Any]]:
        """Extract common patterns across groups of memories.

        Clusters memories by token overlap and generates a synthetic
        'generalization' memory representing the shared pattern.
        """
        if len(memories) < 3:
            return []

        # Simple clustering: group memories by shared tokens
        candidates: list[dict[str, Any]] = []
        all_tokens = [_extract_tokens(m.get("content", "")) for m in memories]

        for i in range(len(memories)):
            if len(candidates) >= max_new:
                break
            for j in range(i + 1, len(memories)):
                if len(candidates) >= max_new:
                    break
                tokens_i = all_tokens[i]
                tokens_j = all_tokens[j]
                shared = tokens_i & tokens_j
                if len(shared) >= 2:
                    # Found a pair with substantial token overlap
                    # Try to find a third that also shares these tokens
                    for k in range(j + 1, len(memories)):
                        tokens_k = all_tokens[k]
                        triple_shared = shared & tokens_k
                        if len(triple_shared) >= 2:
                            m_i, m_j, m_k = memories[i], memories[j], memories[k]
                            # Build a generalization from the shared tokens
                            shared_list = sorted(triple_shared)
                            pattern = ", ".join(shared_list[:8])
                            generalization_content = (
                                f"Generalized pattern: memories share common "
                                f"themes [{pattern}] suggesting a recurring "
                                f"concept across multiple experiences"
                            )
                            summary = f"Synthetic generalization on theme '{pattern[:80]}'"
                            source_ids = [
                                m_i.get("id", ""),
                                m_j.get("id", ""),
                                m_k.get("id", ""),
                            ]
                            source_ids_json = json.dumps(source_ids)

                            result = self.store(
                                workspace_id=workspace_id,
                                content=generalization_content,
                                summary=summary,
                                memory_type=SYNTHETIC_MEMORY_TYPE,
                                confidence=0.7,
                                source_session_id="",
                                entities_json=source_ids_json,
                            )
                            mem_id = result.get("id", "")
                            candidates.append({
                                "id": mem_id,
                                "content": generalization_content,
                                "summary": summary,
                                "strategy": "generalize",
                                "source_memory_ids": source_ids,
                                "shared_tokens": shared_list[:8],
                            })

                            self._log_dream_event(
                                workspace_id,
                                strategy="generalize",
                                generated_id=mem_id,
                                source_ids=source_ids,
                                summary=summary,
                            )
                            break  # One generalization per (i,j) pair
        return candidates

    def _synthesize_fill_gaps(
        self,
        workspace_id: str,
        memories: list[dict[str, Any]],
        max_new: int = 5,
    ) -> list[dict[str, Any]]:
        """Infer missing or implicit information from existing memories.

        Finds memories that mention the same entity/topic and generates
        a synthetic memory that fills a plausible gap — something that
        is implied but not explicitly stated.
        """
        if len(memories) < 2:
            return []

        results: list[dict[str, Any]] = []

        # Group memories by shared entities (from entities_json)
        entity_groups: dict[str, list[dict[str, Any]]] = {}
        for m in memories:
            entities_raw = m.get("entities_json", "{}")
            if isinstance(entities_raw, str) and entities_raw:
                try:
                    entities = json.loads(entities_raw)
                    if isinstance(entities, dict):
                        for ent in entities.values():
                            if isinstance(ent, str) and ent:
                                entity_groups.setdefault(ent, []).append(m)
                    elif isinstance(entities, list):
                        for ent in entities:
                            if isinstance(ent, str) and ent:
                                entity_groups.setdefault(ent, []).append(m)
                except (json.JSONDecodeError, TypeError):
                    pass

        # Also group by frequent tokens as a fallback
        token_groups: dict[str, list[dict[str, Any]]] = {}
        if not entity_groups:
            for m in memories:
                tokens = _extract_tokens(m.get("content", ""))
                for tok in list(tokens)[:3]:  # Use top 3 tokens
                    token_groups.setdefault(tok, []).append(m)

        groups = entity_groups if entity_groups else token_groups

        for group_key, group_mems in groups.items():
            if len(results) >= max_new:
                break
            if len(group_mems) < 2:
                continue

            # Extract all contents for this group
            contents = [m.get("content", "") for m in group_mems if m.get("content")]
            if len(contents) < 2:
                continue

            # Pick two representative memories and synthesize a gap-fill
            m_a, m_b = group_mems[0], group_mems[1]
            content_a = m_a.get("content", "")
            content_b = m_b.get("content", "")

            gap_content = (
                f"Inferred connection: based on memory '{content_a[:100]}…' "
                f"and '{content_b[:100]}…' it is plausible that "
                f"there is an unstated relationship involving '{group_key}'"
            )
            summary = f"Synthetic gap-fill inference about '{group_key}'"
            source_ids = [m_a.get("id", ""), m_b.get("id", "")]
            source_ids_json = json.dumps(source_ids)

            result = self.store(
                workspace_id=workspace_id,
                content=gap_content,
                summary=summary,
                memory_type=SYNTHETIC_MEMORY_TYPE,
                confidence=0.5,  # Lower confidence for inferred connections
                source_session_id="",
                entities_json=source_ids_json,
            )
            mem_id = result.get("id", "")
            results.append({
                "id": mem_id,
                "content": gap_content,
                "summary": summary,
                "strategy": "fill_gaps",
                "source_memory_ids": source_ids,
                "group_key": group_key,
            })

            self._log_dream_event(
                workspace_id,
                strategy="fill_gaps",
                generated_id=mem_id,
                source_ids=source_ids,
                summary=summary,
            )

        return results

    def _synthesize_contrast(
        self,
        workspace_id: str,
        memories: list[dict[str, Any]],
        max_new: int = 5,
    ) -> list[dict[str, Any]]:
        """Find contradictory or contrasting pairs of memories.

        Uses token overlap to find memories that discuss similar topics
        but with conflicting confidence, sentiment, or content direction.
        """
        if len(memories) < 2:
            return []

        results: list[dict[str, Any]] = []

        for i in range(len(memories)):
            if len(results) >= max_new:
                break
            for j in range(i + 1, len(memories)):
                if len(results) >= max_new:
                    break

                m1 = memories[i]
                m2 = memories[j]

                content1 = m1.get("content", "")
                content2 = m2.get("content", "")
                if not content1 or not content2:
                    continue

                tokens1 = _extract_tokens(content1)
                tokens2 = _extract_tokens(content2)
                jaccard = _jaccard_similarity(tokens1, tokens2)

                # Moderate overlap suggests same topic but possibly different view
                if 0.2 <= jaccard <= 0.6:
                    # Check for confidence divergence
                    conf1 = m1.get("confidence", 0.5)
                    conf2 = m2.get("confidence", 0.5)
                    if isinstance(conf1, str):
                        try:
                            conf1 = float(conf1)
                        except (ValueError, TypeError):
                            conf1 = 0.5
                    if isinstance(conf2, str):
                        try:
                            conf2 = float(conf2)
                        except (ValueError, TypeError):
                            conf2 = 0.5

                    contrast_content = (
                        f"Contrast detected: '{content1[:120]}…' and "
                        f"'{content2[:120]}…' share topic overlap "
                        f"(jaccard={jaccard:.2f}) but may represent "
                        f"different perspectives or contradictions"
                    )
                    summary = (
                        f"Synthetic contrast between topic-overlapping "
                        f"memories (jaccard={jaccard:.2f})"
                    )
                    source_ids = [m1.get("id", ""), m2.get("id", "")]
                    source_ids_json = json.dumps(source_ids)

                    result = self.store(
                        workspace_id=workspace_id,
                        content=contrast_content,
                        summary=summary,
                        memory_type=SYNTHETIC_MEMORY_TYPE,
                        confidence=min(0.8, 0.3 + abs(conf1 - conf2)),
                        source_session_id="",
                        entities_json=source_ids_json,
                    )
                    mem_id = result.get("id", "")
                    results.append({
                        "id": mem_id,
                        "content": contrast_content,
                        "summary": summary,
                        "strategy": "contrast",
                        "source_memory_ids": source_ids,
                        "jaccard": round(jaccard, 4),
                    })

                    self._log_dream_event(
                        workspace_id,
                        strategy="contrast",
                        generated_id=mem_id,
                        source_ids=source_ids,
                        summary=summary,
                    )

        return results

    # ------------------------------------------------------------------
    # 2. get_dream_log — history of dream/synthesis sessions
    # ------------------------------------------------------------------

    def get_dream_log(self, workspace_id: str) -> list[dict[str, Any]]:
        """Get the history of dream/synthesis sessions for a workspace.

        Dream log entries are stored as memories with
        ``memory_type="dream_log"``.  Returns them ordered by creation
        time (newest first).

        Args:
            workspace_id: Target workspace.

        Returns:
            List of dream-log entry dicts, each with keys: ``id``,
            ``strategy``, ``generated_id``, ``source_ids``, ``summary``,
            ``created_at``.
        """
        rows = self._query(
            "memory",
            workspace_id=workspace_id,
            filter_dict={
                "workspace_id": workspace_id,
                "memory_type": DREAM_LOG_MEMORY_TYPE,
            },
        )
        # Parse content JSON and enrich
        results: list[dict[str, Any]] = []
        for r in rows:
            content_raw = r.get("content", "{}")
            try:
                details = json.loads(content_raw) if isinstance(content_raw, str) else {}
            except (json.JSONDecodeError, TypeError):
                details = {}
            results.append({
                "id": r.get("id", ""),
                "workspace_id": r.get("workspace_id", workspace_id),
                "strategy": details.get("strategy", ""),
                "generated_id": details.get("generated_id", ""),
                "source_ids": details.get("source_ids", []),
                "summary": details.get("summary", r.get("summary", "")),
                "created_at": r.get("created_at", 0),
                "content_raw": content_raw,
            })

        # Sort newest first
        results.sort(key=lambda x: x.get("created_at", 0), reverse=True)
        return results

    # ------------------------------------------------------------------
    # 3. run_dream_cycle — full dream cycle
    # ------------------------------------------------------------------

    def run_dream_cycle(
        self,
        workspace_id: str,
        strategies: list[str] | None = None,
        max_new: int = 5,
    ) -> dict[str, Any]:
        """Run a full dream cycle with multiple strategies.

        This orchestrates multiple synthesis strategies in one session,
        returning a consolidated report of all generated memories.

        Args:
            workspace_id: Target workspace.
            strategies: List of strategies to run.  Defaults to
                ``["connect", "generalize"]``.
            max_new: Maximum total new synthetic memories to generate.

        Returns:
            Dict with keys:
            - ``results``: list of all generated memories.
            - ``total_generated``: count of generated memories.
            - ``strategies_run``: list of strategies that were executed.
            - ``timestamp``: unix seconds of the cycle.
        """
        if strategies is None:
            strategies = ["connect", "generalize"]

        timestamp = _now_seconds()
        all_results: list[dict[str, Any]] = []
        per_strategy = max(1, max_new // len(strategies))

        for strat in strategies:
            results = self.synthesize_memories(
                workspace_id=workspace_id,
                source_ids=None,
                strategy=strat,
                max_new=per_strategy,
            )
            all_results.extend(results)

        # Trim to max_new
        all_results = all_results[:max_new]

        # Create a session-level dream log entry
        cycle_summary = (
            f"Dream cycle: ran {len(strategies)} strategies "
            f"({', '.join(strategies)}), generated {len(all_results)} memories"
        )
        cycle_content = json.dumps({
            "strategies": strategies,
            "total_generated": len(all_results),
            "generated_ids": [r.get("id", "") for r in all_results],
            "timestamp": timestamp,
        })
        self.store(
            workspace_id=workspace_id,
            content=cycle_content,
            summary=cycle_summary,
            memory_type=DREAM_LOG_MEMORY_TYPE,
            confidence=1.0,
        )

        return {
            "results": all_results,
            "total_generated": len(all_results),
            "strategies_run": strategies,
            "timestamp": timestamp,
        }

    # ------------------------------------------------------------------
    # 4. schedule_dreaming — schedule recurring dreaming
    # ------------------------------------------------------------------

    def schedule_dreaming(
        self,
        workspace_id: str,
        interval_hours: int = 24,
        strategies: list[str] | None = None,
    ) -> dict[str, Any]:
        """Schedule recurring dreaming for a workspace.

        Stores the schedule configuration in the ``workspace_config`` table
        (or as a dream_log memory if config table is unavailable).  The
        actual scheduling execution is expected to be handled externally
        (cron, task queue, etc.).

        Args:
            workspace_id: Target workspace.
            interval_hours: Hours between dream cycles (default 24).
            strategies: List of strategies for each cycle.  Defaults to
                ``["connect"]``.

        Returns:
            The stored schedule config dict.
        """
        if strategies is None:
            strategies = ["connect"]

        config = {
            "interval_hours": interval_hours,
            "strategies": strategies,
            "enabled": True,
            "last_run": 0,
            "next_run": _now_seconds() + interval_hours * 3600,
            "created_at": _now_seconds(),
        }

        content_json = json.dumps(config)
        summary = (
            f"Dream schedule: every {interval_hours}h, "
            f"strategies={strategies}"
        )

        # Store as a dream_log memory so it appears in the dream log
        self.store(
            workspace_id=workspace_id,
            content=content_json,
            summary=summary,
            memory_type=DREAM_LOG_MEMORY_TYPE,
            confidence=1.0,
        )

        # Also try to store in workspace_config for persistence
        try:
            self._call(
                "set_workspace_config",
                [workspace_id, "dream_schedule", content_json],
            )
        except Exception:
            logger.info(
                "schedule_dreaming: workspace_config table may not exist; "
                "config stored as dream_log memory only"
            )

        config["status"] = "scheduled"
        return config

    # ------------------------------------------------------------------
    # 5. get_forgetting_curve — memory strength decay curves
    # ------------------------------------------------------------------

    def get_forgetting_curve(
        self,
        workspace_id: str,
        memory_id: str | None = None,
    ) -> list[dict[str, Any]]:
        """Compute forgetting curves for memories in a workspace.

        Mnemosyne parity: models memory strength over time using Weibull or
        linear decay, projected over a 90-day horizon at daily intervals.

        Args:
            workspace_id: Target workspace.
            memory_id: Optional specific memory ID.  If ``None``, returns
                curves for all active memories (aggregated).

        Returns:
            List of dicts, each with keys: ``memory_id``, ``age_days``,
            ``current_strength``, ``curve`` (list of
            ``{"day": int, "strength": float}``), and ``model``.
        """
        if memory_id:
            rows = self._query("memory", filter_dict={"id": memory_id})
        else:
            rows = self._query(
                "memory",
                workspace_id=workspace_id,
                filter_dict={"workspace_id": workspace_id},
            )

        if not rows:
            return []

        # Try to get the decay model config for this workspace
        model = "linear"
        decay_rate = _DEFAULT_DECAY_RATE
        max_days = _DEFAULT_MAX_DAYS
        weibull_shape = _DEFAULT_WEIBULL_SHAPE
        weibull_scale = _DEFAULT_WEIBULL_SCALE
        try:
            config_rows = self._query(
                "workspace_config",
                filter_dict={"id": workspace_id},
            )
            if config_rows:
                cfg = config_rows[0]
                if isinstance(cfg, dict):
                    model = cfg.get("decay_model", "linear")
                    decay_rate = float(cfg.get("decay_rate", decay_rate))
                    max_days = int(cfg.get("max_days", max_days))
                    weibull_shape = float(cfg.get("weibull_shape", weibull_shape))
                    weibull_scale = float(cfg.get("weibull_scale", weibull_scale))
        except Exception:
            pass  # Use defaults

        results: list[dict[str, Any]] = []
        for mem in rows:
            mem_id = mem.get("id", "")
            age_days = _compute_memory_age_days(mem)
            current = _compute_memory_strength(
                mem, model, decay_rate, max_days, weibull_shape, weibull_scale
            )

            # Generate 90-day projection at daily intervals
            horizon = 90
            curve: list[dict[str, Any]] = []
            for day in range(horizon + 1):
                t = age_days + day
                if model == "weibull":
                    strength = _weibull_decay(t, weibull_shape, weibull_scale)
                else:
                    strength = _linear_decay(t, decay_rate, max_days)
                curve.append({"day": day, "strength": round(strength, 6)})

            results.append({
                "memory_id": mem_id,
                "age_days": round(age_days, 4),
                "current_strength": round(current, 6),
                "model": model,
                "decay_rate": decay_rate,
                "max_days": max_days,
                "curve": curve,
            })

        # Sort by current strength ascending (most forgotten first)
        results.sort(key=lambda x: x["current_strength"])
        return results

    # ------------------------------------------------------------------
    # 6. simulate_cramming — simulate spaced repetition impact
    # ------------------------------------------------------------------

    def simulate_cramming(
        self,
        workspace_id: str,
        memory_ids: list[str],
        review_times: list[float],
    ) -> list[dict[str, Any]]:
        """Simulate the effect of spaced-repetition review on memory strength.

        Uses a simplified SM-2-inspired model: each review boosts strength
        and resets the decay clock partially, simulating the spacing effect.

        Args:
            workspace_id: Target workspace.
            memory_ids: List of memory IDs to simulate.
            review_times: List of review time points in days from now
                (e.g., ``[1, 7, 30]`` for reviews at 1, 7, and 30 days).

        Returns:
            List of dicts, one per memory, each with keys: ``memory_id``,
            ``content``, ``baseline_curve`` (strength without review),
            ``simulated_curve`` (strength with review), and
            ``boost`` (improvement at day 90).
        """
        if not review_times:
            review_times = [1, 7, 30]  # Default: 1 day, 1 week, 1 month

        review_times = sorted(review_times)
        horizon = 90

        rows: list[dict[str, Any]] = []
        for mid in memory_ids:
            r = self._query("memory", filter_dict={"id": mid})
            if r:
                rows.append(r[0])

        if not rows:
            return []

        # Use linear decay model for simulation
        decay_rate = _DEFAULT_DECAY_RATE
        max_days = _DEFAULT_MAX_DAYS

        results: list[dict[str, Any]] = []
        for mem in rows:
            mem_id = mem.get("id", "")
            age_days = _compute_memory_age_days(mem)
            confidence = mem.get("confidence", 0.8)
            if isinstance(confidence, str):
                try:
                    confidence = float(confidence)
                except (ValueError, TypeError):
                    confidence = 0.8

            # Baseline: no review
            baseline_curve: list[dict[str, Any]] = []
            for day in range(horizon + 1):
                t = age_days + day
                strength = confidence * _linear_decay(t, decay_rate, max_days)
                baseline_curve.append({"day": day, "strength": round(strength, 6)})

            # Simulated: with reviews
            sim_curve: list[dict[str, Any]] = []
            current_strength = confidence
            current_age = age_days

            for day in range(horizon + 1):
                # Apply any review happening at this day
                while review_times and abs(review_times[0] - day) < 0.5:
                    review_times.pop(0)
                    # SM-2-like boost: reset partial decay and boost confidence
                    boost_factor = 1.0 + 0.3 * (1.0 - current_strength)
                    current_strength = min(1.0, current_strength * boost_factor)
                    current_age = max(0, current_age * 0.5)  # Halve effective age

                # Apply decay
                day_strength = current_strength * _linear_decay(
                    day, decay_rate * 0.5, max_days
                )
                sim_curve.append({"day": day, "strength": round(day_strength, 6)})

            baseline_end = baseline_curve[-1]["strength"] if baseline_curve else 0.0
            sim_end = sim_curve[-1]["strength"] if sim_curve else 0.0
            boost = sim_end - baseline_end

            results.append({
                "memory_id": mem_id,
                "content": _make_snippet(mem.get("content", "")),
                "baseline_curve": baseline_curve,
                "simulated_curve": sim_curve,
                "boost": round(boost, 6),
                "confidence": confidence,
            })

        return results

    # ------------------------------------------------------------------
    # 7. calculate_memory_health — stats on freshness, decay, coverage
    # ------------------------------------------------------------------

    def calculate_memory_health(self, workspace_id: str) -> dict[str, Any]:
        """Compute memory health metrics for a workspace.

        Analyses memory freshness (age distribution), decay (strength
        distribution), and coverage (topic diversity) to produce a
        comprehensive health report.

        Args:
            workspace_id: Target workspace.

        Returns:
            Dict with keys:
            - ``total_memories``: count of all memories.
            - ``active_memories``: count of active memories.
            - ``synthetic_memories``: count of synthetic memories.
            - ``avg_age_days``: average memory age in days.
            - ``avg_strength``: average memory strength.
            - ``strength_distribution``: counts of weak/medium/strong memories.
            - ``decay_rate``: average decay rate across memories.
            - ``freshness_score``: composite freshness 0.0–1.0.
            - ``coverage_estimate``: estimated topic coverage score 0.0–1.0.
            - ``health_score``: overall health composite 0.0–1.0.
            - ``recommendations``: list of suggested actions.
        """
        rows = self._query(
            "memory",
            workspace_id=workspace_id,
            filter_dict={"workspace_id": workspace_id},
        )

        total = len(rows)
        if total == 0:
            return {
                "total_memories": 0,
                "active_memories": 0,
                "synthetic_memories": 0,
                "avg_age_days": 0.0,
                "avg_strength": 0.0,
                "strength_distribution": {"weak": 0, "medium": 0, "strong": 0},
                "decay_rate": 0.0,
                "freshness_score": 0.0,
                "coverage_estimate": 0.0,
                "health_score": 0.0,
                "recommendations": ["No memories found — start storing experiences."],
            }

        active = 0
        synthetic = 0
        total_age_days = 0.0
        total_strength = 0.0
        weak = 0
        medium = 0
        strong = 0
        top_tokens: set[str] = set()

        for mem in rows:
            is_active = mem.get("is_active", True)
            if isinstance(is_active, bool) and not is_active:
                continue
            active += 1

            mem_type = mem.get("memory_type", "")
            if mem_type == SYNTHETIC_MEMORY_TYPE:
                synthetic += 1

            age = _compute_memory_age_days(mem)
            total_age_days += age

            strength = _compute_memory_strength(mem)
            total_strength += strength

            if strength < 0.3:
                weak += 1
            elif strength < 0.7:
                medium += 1
            else:
                strong += 1

            # Collect tokens for coverage estimation
            content = mem.get("content", "")
            if content:
                top_tokens.update(_extract_tokens(content))

        avg_age = total_age_days / total if total else 0.0
        avg_strength = total_strength / total if total else 0.0

        # Freshness score: inverse of avg age normalised to 90-day window
        freshness = max(0.0, 1.0 - avg_age / 90.0)

        # Coverage estimate: token diversity relative to size
        coverage = min(1.0, len(top_tokens) / (total * 2 + 1))

        # Health score: weighted composite
        health = (
            0.3 * avg_strength
            + 0.3 * freshness
            + 0.2 * coverage
            + 0.2 * min(1.0, active / max(1, total))
        )

        recommendations: list[str] = []
        if avg_strength < 0.4:
            recommendations.append(
                "Average memory strength is low — consider reinforcing key memories "
                "or running a dream cycle to generate connections."
            )
        if avg_age > 30:
            recommendations.append(
                f"Memories are aging (avg {avg_age:.0f} days) — consider review or "
                f"cramming simulation to identify candidates for reinforcement."
            )
        if synthetic / max(1, total) < 0.1 and total > 10:
            recommendations.append(
                "Few synthetic memories — run a dream cycle to improve "
                "memory interconnectivity."
            )
        if weak > total * 0.5:
            recommendations.append(
                "More than half of memories have low strength — review and "
                "reinforce or archive stale memories."
            )
        if not recommendations:
            recommendations.append("Memory health is good — no action required.")

        return {
            "total_memories": total,
            "active_memories": active,
            "synthetic_memories": synthetic,
            "avg_age_days": round(avg_age, 4),
            "avg_strength": round(avg_strength, 6),
            "strength_distribution": {
                "weak": weak,
                "medium": medium,
                "strong": strong,
            },
            "freshness_score": round(freshness, 4),
            "coverage_estimate": round(coverage, 4),
            "health_score": round(health, 4),
            "recommendations": recommendations,
        }

    # ------------------------------------------------------------------
    # 8. forgetting_curve_predict — predict memory strength over time
    # ------------------------------------------------------------------

    def forgetting_curve_predict(
        self,
        workspace_id: str,
        memory: dict[str, Any],
        days_from_now: float = 30.0,
    ) -> dict[str, Any]:
        """Predict memory strength at a future point in time.

        Unlike :meth:`get_forgetting_curve` which returns a full curve
        for multiple memories, this method takes a single memory dict
        (e.g. from a query result) and returns a simplified forecast
        at a specific future date.

        Args:
            workspace_id: Target workspace.
            memory: A memory dict (must have ``created_at`` and optionally
                ``confidence``).  Can be a raw memory row or a dict with
                those keys.
            days_from_now: How many days into the future to predict.

        Returns:
            Dict with keys: ``memory_id``, ``current_strength``,
            ``predicted_strength``, ``days_from_now``, ``age_at_prediction``,
            ``model``, ``strength_delta``.
        """
        # Try to get the decay model config for this workspace
        model = "linear"
        decay_rate = _DEFAULT_DECAY_RATE
        max_days = _DEFAULT_MAX_DAYS
        weibull_shape = _DEFAULT_WEIBULL_SHAPE
        weibull_scale = _DEFAULT_WEIBULL_SCALE
        try:
            config_rows = self._query(
                "workspace_config",
                filter_dict={"id": workspace_id},
            )
            if config_rows:
                cfg = config_rows[0]
                if isinstance(cfg, dict):
                    model = cfg.get("decay_model", "linear")
                    decay_rate = float(cfg.get("decay_rate", decay_rate))
                    max_days = int(cfg.get("max_days", max_days))
                    weibull_shape = float(cfg.get("weibull_shape", weibull_shape))
                    weibull_scale = float(cfg.get("weibull_scale", weibull_scale))
        except Exception:
            pass

        age_days = _compute_memory_age_days(memory)
        current = _compute_memory_strength(
            memory, model, decay_rate, max_days, weibull_shape, weibull_scale
        )

        future_age = age_days + days_from_now
        if model == "weibull":
            predicted = _weibull_decay(future_age, weibull_shape, weibull_scale)
        else:
            predicted = _linear_decay(future_age, decay_rate, max_days)

        # Scale by confidence
        confidence = memory.get("confidence", 0.8)
        if isinstance(confidence, str):
            try:
                confidence = float(confidence)
            except (ValueError, TypeError):
                confidence = 0.8
        predicted *= confidence

        return {
            "memory_id": memory.get("id", ""),
            "current_strength": round(current, 6),
            "predicted_strength": round(predicted, 6),
            "days_from_now": days_from_now,
            "age_at_prediction": round(future_age, 4),
            "model": model,
            "strength_delta": round(predicted - current, 6),
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _log_dream_event(
        self,
        workspace_id: str,
        strategy: str,
        generated_id: str,
        source_ids: list[str],
        summary: str,
    ) -> None:
        """Store a dream-log entry for a single synthesis event.

        Entries are stored as memories with ``memory_type="dream_log"``
        so they appear in ``get_dream_log`` results and are searchable.
        """
        content = json.dumps({
            "strategy": strategy,
            "generated_id": generated_id,
            "source_ids": source_ids,
            "summary": summary,
            "timestamp": _now_seconds(),
        })
        try:
            self.store(
                workspace_id=workspace_id,
                content=content,
                summary=summary,
                memory_type=DREAM_LOG_MEMORY_TYPE,
                confidence=1.0,
            )
        except Exception as exc:
            logger.warning("Failed to log dream event: %s", exc)


# ── Re-export helper for tests ──────────────────────────────────────────────

def _make_snippet(text: str, max_chars: int = 120) -> str:
    """Truncate text at word boundary for display."""
    if not text:
        return ""
    if len(text) <= max_chars:
        return text
    truncated = text[:max_chars]
    last_space = truncated.rfind(" ")
    if last_space > max_chars // 2:
        truncated = truncated[:last_space]
    return truncated.rstrip() + "..."
