"""Autonomous reflection loop — Hindsight parity.

Provides an autonomous reflection system that periodically reflects on
accumulated memories, generates insights (patterns, contradictions, gaps,
observations, connections, syntheses), and maintains a reflection state
machine across cycles.

Reference: https://github.com/vectorize-io/hindsight
"""
from __future__ import annotations

import json
import time
from typing import Any


class ReflectionLoopMixin:
    """Mixin for autonomous reflection loop lifecycle management.

    Provides methods to create, run, and manage reflection sessions
    that autonomously analyze accumulated memories for patterns,
    contradictions, knowledge gaps, and insights.

    Typical usage::

        client = Client(...)

        # Create a session
        session = client.create_reflection_session(
            workspace_id="ws-1",
            peer_id="agent-1",
            config={
                "interval_minutes": 60,
                "max_cycles": 100,
                "focus_areas": ["user_preferences", "domain_knowledge"],
                "min_confidence": 0.3,
                "llm_model": "default"
            }
        )
        session_id = session["session_id"]

        # Run a reflection cycle
        client.start_reflection_cycle("ws-1", session_id)

        # Store insights
        client.store_reflection_insight(
            workspace_id="ws-1",
            session_id=session_id,
            content="User consistently prefers async communication",
            confidence=0.85,
            insight_type="pattern",
            source_memory_ids=["mem-1", "mem-2"],
            source_note_ids=[]
        )

        # Complete session
        client.complete_reflection_session("ws-1", session_id, "completed")

        # View results
        sessions = client.get_reflection_sessions("ws-1")
        insights = client.get_reflection_insights("ws-1", session_id)

        # Delete
        client.delete_reflection_session("ws-1", session_id)
    """

    def create_reflection_session(
        self,
        workspace_id: str,
        peer_id: str,
        config: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Create a new autonomous reflection session.

        Args:
            workspace_id: Target workspace.
            peer_id: The agent / peer initiating reflection.
            config: Configuration dict with keys:
                - interval_minutes (int): Min between cycles (default: 60)
                - max_cycles (int): Max reflection cycles (default: 100)
                - focus_areas (list[str]): Areas to focus on (default: [])
                - min_confidence (float): Min confidence to accept insights (default: 0.3)
                - llm_model (str): Model to use (default: "default")

        Returns:
            Reducer result with session_id.
        """
        if config is None:
            config = {}
        config_json = json.dumps(config)
        return self._call(
            "create_reflection_session",
            [workspace_id, peer_id, config_json],
        )

    def start_reflection_cycle(
        self,
        workspace_id: str,
        session_id: str,
    ) -> dict[str, Any]:
        """Start a new reflection cycle within a session.

        Increments the cycle counter and updates status to running.

        Args:
            workspace_id: Target workspace.
            session_id: Session to cycle.

        Returns:
            Reducer status.
        """
        return self._call(
            "start_reflection_cycle",
            [workspace_id, session_id],
        )

    def store_reflection_insight(
        self,
        workspace_id: str,
        session_id: str,
        content: str,
        confidence: float,
        insight_type: str,
        source_memory_ids: list[str] | None = None,
        source_note_ids: list[str] | None = None,
    ) -> dict[str, Any]:
        """Store an insight generated by a reflection cycle.

        Args:
            workspace_id: Target workspace.
            session_id: Session this insight belongs to.
            content: The insight text.
            confidence: Confidence score (0.0-1.0).
            insight_type: Type: "pattern", "contradiction", "gap",
                         "observation", "connection", or "synthesis".
            source_memory_ids: Memory IDs that inspired this insight.
            source_note_ids: Note IDs that inspired this insight.

        Returns:
            Reducer status.
        """
        if source_memory_ids is None:
            source_memory_ids = []
        if source_note_ids is None:
            source_note_ids = []
        return self._call(
            "store_reflection_insight",
            [
                workspace_id,
                session_id,
                content,
                confidence,
                insight_type,
                json.dumps(source_memory_ids),
                json.dumps(source_note_ids),
            ],
        )

    def complete_reflection_session(
        self,
        workspace_id: str,
        session_id: str,
        status: str = "completed",
    ) -> dict[str, Any]:
        """Complete a reflection session.

        Args:
            workspace_id: Target workspace.
            session_id: Session to complete.
            status: Final status ("completed" or "failed").

        Returns:
            Reducer status.
        """
        return self._call(
            "complete_reflection_session",
            [workspace_id, session_id, status],
        )

    def get_reflection_sessions(
        self,
        workspace_id: str,
    ) -> list[dict[str, Any]]:
        """Get all reflection sessions for a workspace.

        Args:
            workspace_id: Target workspace.

        Returns:
            List of session dicts.
        """
        result = self._call(
            "get_reflection_sessions",
            [workspace_id],
        )
        raw = result.get("data", result.get("result", "[]"))
        if isinstance(raw, str):
            return json.loads(raw)
        return raw

    def get_reflection_insights(
        self,
        workspace_id: str,
        session_id: str,
    ) -> list[dict[str, Any]]:
        """Get all insights for a reflection session.

        Args:
            workspace_id: Target workspace.
            session_id: Session to get insights for.

        Returns:
            List of insight dicts.
        """
        result = self._call(
            "get_reflection_insights",
            [workspace_id, session_id],
        )
        raw = result.get("data", result.get("result", "[]"))
        if isinstance(raw, str):
            return json.loads(raw)
        return raw

    def delete_reflection_session(
        self,
        workspace_id: str,
        session_id: str,
    ) -> dict[str, Any]:
        """Delete a reflection session and all its insights.

        Args:
            workspace_id: Target workspace.
            session_id: Session to delete.

        Returns:
            Reducer status.
        """
        return self._call(
            "delete_reflection_session",
            [workspace_id, session_id],
        )

    def get_reflection_state(
        self,
        workspace_id: str,
        session_id: str,
    ) -> dict[str, Any]:
        """Get a combined snapshot of reflection state.

        Returns session metadata plus summary stats:
        cycle_count, insights_count, recent insights (last 5),
        status, session age.

        Args:
            workspace_id: Target workspace.
            session_id: Session to inspect.

        Returns:
            Dict with session details, insights summary, and stats.
        """
        # Get sessions
        sessions = self.get_reflection_sessions(workspace_id)
        session = None
        for s in sessions:
            if s.get("id") == session_id or s.get("session_id") == session_id:
                session = s
                break
        if not session:
            return {"error": f"Session {session_id} not found in workspace {workspace_id}"}

        # Get insights
        insights = self.get_reflection_insights(workspace_id, session_id)

        # Build stats
        now = int(time.time() * 1_000_000)
        started = session.get("started_at", now)
        age_micros = now - started
        age_hours = age_micros / 3_600_000_000.0

        # Type breakdown
        type_counts: dict[str, int] = {}
        for ins in insights:
            t = ins.get("insight_type", "unknown")
            type_counts[t] = type_counts.get(t, 0) + 1

        recent = insights[-5:] if len(insights) > 5 else insights

        return {
            "session": session,
            "insights_count": len(insights),
            "type_breakdown": type_counts,
            "age_hours": round(age_hours, 2),
            "recent_insights": recent,
        }
