// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  previousContextPackId: __t.string().name("previous_context_pack_id"),
  queryHash: __t.string().name("query_hash"),
  changedMemoryIdsJson: __t.string().name("changed_memory_ids_json"),
  removedMemoryIdsJson: __t.string().name("removed_memory_ids_json"),
  newMemoriesJson: __t.string().name("new_memories_json"),
  estimatedTokens: __t.u32().name("estimated_tokens"),
  createdAt: __t.i64().name("created_at"),
});
