// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  documentId: __t.string().name("document_id"),
  content: __t.string(),
  chunkIndex: __t.u32().name("chunk_index"),
  embeddingJson: __t.string().name("embedding_json"),
  createdAt: __t.i64().name("created_at"),
});
