// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  title: __t.string(),
  content: __t.string(),
  contentType: __t.string().name("content_type"),
  filePath: __t.string().name("file_path"),
  sourceUrl: __t.string().name("source_url"),
  metadataJson: __t.string().name("metadata_json"),
  chunkCount: __t.u32().name("chunk_count"),
  createdAt: __t.i64().name("created_at"),
  updatedAt: __t.i64().name("updated_at"),
});
