// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.4.1 (commit 07b52763c9da8d7cf79780db222fec1ffcb84070).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AddAliasReducer from "./add_alias_reducer";
import AddChunkReducer from "./add_chunk_reducer";
import AddDynamicContextReducer from "./add_dynamic_context_reducer";
import AddProfileFactReducer from "./add_profile_fact_reducer";
import AssignToCommunityReducer from "./assign_to_community_reducer";
import CleanupExpiredSessionsReducer from "./cleanup_expired_sessions_reducer";
import ComputeGodNodesReducer from "./compute_god_nodes_reducer";
import ComputePagerankReducer from "./compute_pagerank_reducer";
import ComputeCommunityHierarchyReducer from "./compute_community_hierarchy_reducer";
import ConsolidateMemoriesReducer from "./consolidate_memories_reducer";
import CreateApiKeyReducer from "./create_api_key_reducer";
import CreateAuthSessionReducer from "./create_auth_session_reducer";
import CreateCommunityReducer from "./create_community_reducer";
import CreateDirectoryReducer from "./create_directory_reducer";
import CreateDocumentReducer from "./create_document_reducer";
import CreateEdgeReducer from "./create_edge_reducer";
import CreateEntityLinkReducer from "./create_entity_link_reducer";
import CreateInsightReducer from "./create_insight_reducer";
import CreateNodeReducer from "./create_node_reducer";
import CreateNoteReducer from "./create_note_reducer";
import CreatePeerReducer from "./create_peer_reducer";
import CreateSessionReducer from "./create_session_reducer";
import CreateTagReducer from "./create_tag_reducer";
import CreateWorkspaceReducer from "./create_workspace_reducer";
import DeactivateApiKeyReducer from "./deactivate_api_key_reducer";
import DeactivateMemoryReducer from "./deactivate_memory_reducer";
import DecayWeakMemoriesReducer from "./decay_weak_memories_reducer";
import DedupMemoriesReducer from "./dedup_memories_reducer";
import DeleteDirectoryReducer from "./delete_directory_reducer";
import DeleteDocumentReducer from "./delete_document_reducer";
import DeleteEdgeReducer from "./delete_edge_reducer";
import DeleteInsightReducer from "./delete_insight_reducer";
import DeleteMessageReducer from "./delete_message_reducer";
import DeleteNodeReducer from "./delete_node_reducer";
import DeleteNoteReducer from "./delete_note_reducer";
import DeletePeerReducer from "./delete_peer_reducer";
import DeleteWorkspaceReducer from "./delete_workspace_reducer";
import DetectCommunitiesReducer from "./detect_communities_reducer";
import ExpireMemoriesReducer from "./expire_memories_reducer";
import GenerateContextPackReducer from "./generate_context_pack_reducer";
import GetDeltaReducer from "./get_delta_reducer";
import GetPeerMemorySummaryReducer from "./get_peer_memory_summary_reducer";
import GetProfileContextReducer from "./get_profile_context_reducer";
import GetSearchResultsReducer from "./get_search_results_reducer";
import HybridSearchReducer from "./hybrid_search_reducer";
import IndexEntityReducer from "./index_entity_reducer";
import JoinSessionReducer from "./join_session_reducer";
import LeaveSessionReducer from "./leave_session_reducer";
import ManualMaintenanceReducer from "./manual_maintenance_reducer";
import RateMemoryReducer from "./rate_memory_reducer";
import ReinforceMemoryReducer from "./reinforce_memory_reducer";
import RemoveFromIndexReducer from "./remove_from_index_reducer";
import ResolveEntityReducer from "./resolve_entity_reducer";
import RevokeAuthSessionReducer from "./revoke_auth_session_reducer";
import SearchDirectoryContentsReducer from "./search_directory_contents_reducer";
import SearchProfilesReducer from "./search_profiles_reducer";
import SeedCommunitiesReducer from "./seed_communities_reducer";
import SendMessageReducer from "./send_message_reducer";
import StoreContextPackReducer from "./store_context_pack_reducer";
import StoreMemoryReducer from "./store_memory_reducer";
import TagMemoryReducer from "./tag_memory_reducer";
import UntagMemoryReducer from "./untag_memory_reducer";
import UpdateMemoryReducer from "./update_memory_reducer";
import UpdateMemoryTierReducer from "./update_memory_tier_reducer";
import UpdateNoteReducer from "./update_note_reducer";
import UpdatePeerReducer from "./update_peer_reducer";
import UpdateSessionSummaryReducer from "./update_session_summary_reducer";
import UpdateWorkspaceReducer from "./update_workspace_reducer";
import UpsertProfileReducer from "./upsert_profile_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ApiKeyRow from "./api_key_table";
import AuthSessionRow from "./auth_session_table";
import ConsolidationLogRow from "./consolidation_log_table";
import ContextDirectoryRow from "./context_directory_table";
import ContextPackRow from "./context_pack_table";
import DeltaPackRow from "./delta_pack_table";
import DirectoryContentResultRow from "./directory_content_result_table";
import DocChunkRow from "./doc_chunk_table";
import DocumentRow from "./document_table";
import EntityLinkRow from "./entity_link_table";
import GodNodeRow from "./god_node_table";
import HybridResultRow from "./hybrid_result_table";
import PagerankResultRow from "./pagerank_result_table";
import HierarchyClusterRow from "./hierarchy_cluster_table";
import CommunityHierarchyRow from "./community_hierarchy_table";
import InsightRow from "./insight_table";
import KgCommunityRow from "./kg_community_table";
import KgEdgeRow from "./kg_edge_table";
import KgNodeRow from "./kg_node_table";
import MaintenanceScheduleRow from "./maintenance_schedule_table";
import MemoryRow from "./memory_table";
import MemoryFeedbackRow from "./memory_feedback_table";
import MemoryTagRow from "./memory_tag_table";
import MessageRow from "./message_table";
import NoteRow from "./note_table";
import NoteBacklinkRow from "./note_backlink_table";
import PeerRow from "./peer_table";
import PeerSummaryResultRow from "./peer_summary_result_table";
import ProfileRow from "./profile_table";
import ProfileContextResultRow from "./profile_context_result_table";
import SearchIndexRow from "./search_index_table";
import SessionRow from "./session_table";
import SessionParticipantRow from "./session_participant_table";
import TagRow from "./tag_table";
import WorkspaceRow from "./workspace_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  api_key: __table({
    name: 'api_key',
    indexes: [
      { accessor: 'id', name: 'api_key_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'api_key_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ApiKeyRow),
  auth_session: __table({
    name: 'auth_session',
    indexes: [
      { accessor: 'id', name: 'auth_session_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'auth_session_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, AuthSessionRow),
  consolidation_log: __table({
    name: 'consolidation_log',
    indexes: [
      { accessor: 'id', name: 'consolidation_log_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'consolidation_log_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ConsolidationLogRow),
  context_directory: __table({
    name: 'context_directory',
    indexes: [
      { accessor: 'id', name: 'context_directory_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'context_directory_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ContextDirectoryRow),
  context_pack: __table({
    name: 'context_pack',
    indexes: [
      { accessor: 'id', name: 'context_pack_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'context_pack_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ContextPackRow),
  delta_pack: __table({
    name: 'delta_pack',
    indexes: [
      { accessor: 'id', name: 'delta_pack_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'delta_pack_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DeltaPackRow),
  directory_content_result: __table({
    name: 'directory_content_result',
    indexes: [
      { accessor: 'id', name: 'directory_content_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'directory_content_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DirectoryContentResultRow),
  doc_chunk: __table({
    name: 'doc_chunk',
    indexes: [
      { accessor: 'id', name: 'doc_chunk_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'doc_chunk_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DocChunkRow),
  document: __table({
    name: 'document',
    indexes: [
      { accessor: 'id', name: 'document_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'document_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, DocumentRow),
  entity_link: __table({
    name: 'entity_link',
    indexes: [
      { accessor: 'id', name: 'entity_link_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'entity_link_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, EntityLinkRow),
  god_node: __table({
    name: 'god_node',
    indexes: [
      { accessor: 'id', name: 'god_node_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'god_node_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GodNodeRow),
  hybrid_result: __table({
    name: 'hybrid_result',
    indexes: [
      { accessor: 'id', name: 'hybrid_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'hybrid_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, HybridResultRow),
  pagerank_result: __table({
    name: 'pagerank_result',
    indexes: [
      { accessor: 'id', name: 'pagerank_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'pagerank_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PagerankResultRow),
  insight: __table({
    name: 'insight',
    indexes: [
      { accessor: 'id', name: 'insight_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'insight_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, InsightRow),
  kg_community: __table({
    name: 'kg_community',
    indexes: [
      { accessor: 'id', name: 'kg_community_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'kg_community_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, KgCommunityRow),
  kg_edge: __table({
    name: 'kg_edge',
    indexes: [
      { accessor: 'id', name: 'kg_edge_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'kg_edge_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, KgEdgeRow),
  kg_node: __table({
    name: 'kg_node',
    indexes: [
      { accessor: 'id', name: 'kg_node_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'kg_node_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, KgNodeRow),
  hierarchy_cluster: __table({
    name: 'hierarchy_cluster',
    indexes: [
      { accessor: 'id', name: 'hierarchy_cluster_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'hierarchy_cluster_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, HierarchyClusterRow),
  community_hierarchy: __table({
    name: 'community_hierarchy',
    indexes: [
      { accessor: 'id', name: 'community_hierarchy_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'community_hierarchy_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, CommunityHierarchyRow),
  maintenance_schedule: __table({
    name: 'maintenance_schedule',
    indexes: [
      { accessor: 'scheduled_id', name: 'maintenance_schedule_scheduled_id_idx_btree', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'maintenance_schedule_scheduled_id_key', constraint: 'unique', columns: ['scheduledId'] },
    ],
  }, MaintenanceScheduleRow),
  memory: __table({
    name: 'memory',
    indexes: [
      { accessor: 'id', name: 'memory_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'memory_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MemoryRow),
  memory_feedback: __table({
    name: 'memory_feedback',
    indexes: [
      { accessor: 'id', name: 'memory_feedback_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'memory_feedback_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MemoryFeedbackRow),
  memory_tag: __table({
    name: 'memory_tag',
    indexes: [
    ],
    constraints: [
    ],
  }, MemoryTagRow),
  message: __table({
    name: 'message',
    indexes: [
      { accessor: 'id', name: 'message_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'message_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, MessageRow),
  note: __table({
    name: 'note',
    indexes: [
      { accessor: 'id', name: 'note_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'note_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NoteRow),
  note_backlink: __table({
    name: 'note_backlink',
    indexes: [
      { accessor: 'id', name: 'note_backlink_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'note_backlink_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, NoteBacklinkRow),
  peer: __table({
    name: 'peer',
    indexes: [
      { accessor: 'id', name: 'peer_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'peer_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PeerRow),
  peer_summary_result: __table({
    name: 'peer_summary_result',
    indexes: [
      { accessor: 'id', name: 'peer_summary_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'peer_summary_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, PeerSummaryResultRow),
  profile: __table({
    name: 'profile',
    indexes: [
      { accessor: 'id', name: 'profile_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'profile_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ProfileRow),
  profile_context_result: __table({
    name: 'profile_context_result',
    indexes: [
      { accessor: 'id', name: 'profile_context_result_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'profile_context_result_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, ProfileContextResultRow),
  search_index: __table({
    name: 'search_index',
    indexes: [
      { accessor: 'id', name: 'search_index_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'search_index_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SearchIndexRow),
  session: __table({
    name: 'session',
    indexes: [
      { accessor: 'id', name: 'session_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'session_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SessionRow),
  session_participant: __table({
    name: 'session_participant',
    indexes: [
    ],
    constraints: [
    ],
  }, SessionParticipantRow),
  tag: __table({
    name: 'tag',
    indexes: [
      { accessor: 'id', name: 'tag_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'tag_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, TagRow),
  workspace: __table({
    name: 'workspace',
    indexes: [
      { accessor: 'id', name: 'workspace_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'workspace_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, WorkspaceRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("add_alias", AddAliasReducer),
  __reducerSchema("add_chunk", AddChunkReducer),
  __reducerSchema("add_dynamic_context", AddDynamicContextReducer),
  __reducerSchema("add_profile_fact", AddProfileFactReducer),
  __reducerSchema("assign_to_community", AssignToCommunityReducer),
  __reducerSchema("cleanup_expired_sessions", CleanupExpiredSessionsReducer),
  __reducerSchema("compute_god_nodes", ComputeGodNodesReducer),
  __reducerSchema("compute_pagerank", ComputePagerankReducer),
  __reducerSchema("compute_community_hierarchy", ComputeCommunityHierarchyReducer),
  __reducerSchema("consolidate_memories", ConsolidateMemoriesReducer),
  __reducerSchema("create_api_key", CreateApiKeyReducer),
  __reducerSchema("create_auth_session", CreateAuthSessionReducer),
  __reducerSchema("create_community", CreateCommunityReducer),
  __reducerSchema("create_directory", CreateDirectoryReducer),
  __reducerSchema("create_document", CreateDocumentReducer),
  __reducerSchema("create_edge", CreateEdgeReducer),
  __reducerSchema("create_entity_link", CreateEntityLinkReducer),
  __reducerSchema("create_insight", CreateInsightReducer),
  __reducerSchema("create_node", CreateNodeReducer),
  __reducerSchema("create_note", CreateNoteReducer),
  __reducerSchema("create_peer", CreatePeerReducer),
  __reducerSchema("create_session", CreateSessionReducer),
  __reducerSchema("create_tag", CreateTagReducer),
  __reducerSchema("create_workspace", CreateWorkspaceReducer),
  __reducerSchema("deactivate_api_key", DeactivateApiKeyReducer),
  __reducerSchema("deactivate_memory", DeactivateMemoryReducer),
  __reducerSchema("decay_weak_memories", DecayWeakMemoriesReducer),
  __reducerSchema("dedup_memories", DedupMemoriesReducer),
  __reducerSchema("delete_directory", DeleteDirectoryReducer),
  __reducerSchema("delete_document", DeleteDocumentReducer),
  __reducerSchema("delete_edge", DeleteEdgeReducer),
  __reducerSchema("delete_insight", DeleteInsightReducer),
  __reducerSchema("delete_message", DeleteMessageReducer),
  __reducerSchema("delete_node", DeleteNodeReducer),
  __reducerSchema("delete_note", DeleteNoteReducer),
  __reducerSchema("delete_peer", DeletePeerReducer),
  __reducerSchema("delete_workspace", DeleteWorkspaceReducer),
  __reducerSchema("detect_communities", DetectCommunitiesReducer),
  __reducerSchema("expire_memories", ExpireMemoriesReducer),
  __reducerSchema("generate_context_pack", GenerateContextPackReducer),
  __reducerSchema("get_delta", GetDeltaReducer),
  __reducerSchema("get_peer_memory_summary", GetPeerMemorySummaryReducer),
  __reducerSchema("get_profile_context", GetProfileContextReducer),
  __reducerSchema("get_search_results", GetSearchResultsReducer),
  __reducerSchema("hybrid_search", HybridSearchReducer),
  __reducerSchema("index_entity", IndexEntityReducer),
  __reducerSchema("join_session", JoinSessionReducer),
  __reducerSchema("leave_session", LeaveSessionReducer),
  __reducerSchema("manual_maintenance", ManualMaintenanceReducer),
  __reducerSchema("rate_memory", RateMemoryReducer),
  __reducerSchema("reinforce_memory", ReinforceMemoryReducer),
  __reducerSchema("remove_from_index", RemoveFromIndexReducer),
  __reducerSchema("resolve_entity", ResolveEntityReducer),
  __reducerSchema("revoke_auth_session", RevokeAuthSessionReducer),
  __reducerSchema("search_directory_contents", SearchDirectoryContentsReducer),
  __reducerSchema("search_profiles", SearchProfilesReducer),
  __reducerSchema("seed_communities", SeedCommunitiesReducer),
  __reducerSchema("send_message", SendMessageReducer),
  __reducerSchema("store_context_pack", StoreContextPackReducer),
  __reducerSchema("store_memory", StoreMemoryReducer),
  __reducerSchema("tag_memory", TagMemoryReducer),
  __reducerSchema("untag_memory", UntagMemoryReducer),
  __reducerSchema("update_memory", UpdateMemoryReducer),
  __reducerSchema("update_memory_tier", UpdateMemoryTierReducer),
  __reducerSchema("update_note", UpdateNoteReducer),
  __reducerSchema("update_peer", UpdatePeerReducer),
  __reducerSchema("update_session_summary", UpdateSessionSummaryReducer),
  __reducerSchema("update_workspace", UpdateWorkspaceReducer),
  __reducerSchema("upsert_profile", UpsertProfileReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.4.1" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

