// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  peerId: __t.string().name("peer_id"),
  content: __t.string(),
  insightType: __t.string().name("insight_type"),
  sourceMemoryIdsJson: __t.string().name("source_memory_ids_json"),
  confidence: __t.f64(),
  createdAt: __t.i64().name("created_at"),
});
