// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  sourceNodeId: __t.string().name("source_node_id"),
  targetNodeId: __t.string().name("target_node_id"),
  relation: __t.string(),
  weight: __t.f64(),
  confidence: __t.string(),
  metadataJson: __t.string().name("metadata_json"),
  createdAt: __t.i64().name("created_at"),
});
