// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  label: __t.string(),
  nodeType: __t.string().name("node_type"),
  summary: __t.string(),
  metadataJson: __t.string().name("metadata_json"),
  communityId: __t.u64().name("community_id"),
  embeddingJson: __t.string().name("embedding_json"),
  createdAt: __t.i64().name("created_at"),
});
