// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  peerId: __t.string().name("peer_id"),
  observerId: __t.string().name("observer_id"),
  memoryType: __t.string().name("memory_type"),
  content: __t.string(),
  summary: __t.string(),
  entitiesJson: __t.string().name("entities_json"),
  confidence: __t.f64(),
  sourceSessionId: __t.string().name("source_session_id"),
  sourceMessageId: __t.string().name("source_message_id"),
  isActive: __t.bool().name("is_active"),
  createdAt: __t.i64().name("created_at"),
  expiresAt: __t.i64().name("expires_at"),
  updatedAt: __t.i64().name("updated_at"),
  tier: __t.string(),
  accessCount: __t.u64().name("access_count"),
  strength: __t.f64(),
  version: __t.u32(),
  validFrom: __t.i64().name("valid_from"),
  parentDirectoryId: __t.string().name("parent_directory_id"),
  consolidatedTo: __t.string().name("consolidated_to"),
  trustScore: __t.f64().name("trust_score"),
  feedbackCount: __t.u32().name("feedback_count"),
});
