// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  workspaceId: __t.string().name("workspace_id"),
  entityType: __t.string().name("entity_type"),
  entityId: __t.string().name("entity_id"),
  content: __t.string(),
  embeddingJson: __t.string().name("embedding_json"),
  bm25Text: __t.string().name("bm_25_text"),
  tokens: __t.u32(),
  createdAt: __t.i64().name("created_at"),
});
