// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  workspaceId: __t.string(),
  peerId: __t.string(),
  observerId: __t.string(),
  memoryType: __t.string(),
  content: __t.string(),
  summary: __t.string(),
  entitiesJson: __t.string(),
  confidence: __t.f64(),
  sourceSessionId: __t.string(),
  sourceMessageId: __t.string(),
};
