// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ApiKey = __t.object("ApiKey", {
  id: __t.string(),
  workspaceId: __t.string(),
  keyHash: __t.string(),
  name: __t.string(),
  permissions: __t.string(),
  isActive: __t.bool(),
  createdAt: __t.i64(),
  lastUsedAt: __t.i64(),
});
export type ApiKey = __Infer<typeof ApiKey>;

export const AuthSession = __t.object("AuthSession", {
  id: __t.string(),
  peerId: __t.string(),
  tokenHash: __t.string(),
  expiresAt: __t.i64(),
  createdAt: __t.i64(),
});
export type AuthSession = __Infer<typeof AuthSession>;

export const ConsolidationLog = __t.object("ConsolidationLog", {
  id: __t.string(),
  workspaceId: __t.string(),
  consolidationType: __t.string(),
  sourceMemoryIds: __t.string(),
  targetMemoryId: __t.string(),
  createdAt: __t.i64(),
});
export type ConsolidationLog = __Infer<typeof ConsolidationLog>;

export const ContextDirectory = __t.object("ContextDirectory", {
  id: __t.string(),
  workspaceId: __t.string(),
  name: __t.string(),
  path: __t.string(),
  parentId: __t.string(),
  description: __t.string(),
  createdAt: __t.i64(),
  updatedAt: __t.i64(),
});
export type ContextDirectory = __Infer<typeof ContextDirectory>;

export const ContextPack = __t.object("ContextPack", {
  id: __t.string(),
  workspaceId: __t.string(),
  queryHash: __t.string(),
  packJson: __t.string(),
  tokenCount: __t.u32(),
  createdAt: __t.i64(),
});
export type ContextPack = __Infer<typeof ContextPack>;

export const DeltaPack = __t.object("DeltaPack", {
  id: __t.string(),
  workspaceId: __t.string(),
  previousContextPackId: __t.string(),
  queryHash: __t.string(),
  changedMemoryIdsJson: __t.string(),
  removedMemoryIdsJson: __t.string(),
  newMemoriesJson: __t.string(),
  estimatedTokens: __t.u32(),
  createdAt: __t.i64(),
});
export type DeltaPack = __Infer<typeof DeltaPack>;

export const DirectoryContentResult = __t.object("DirectoryContentResult", {
  id: __t.string(),
  workspaceId: __t.string(),
  directoryPath: __t.string(),
  directoryId: __t.string(),
  subdirectoryIdsJson: __t.string(),
  memoryIdsJson: __t.string(),
  createdAt: __t.i64(),
});
export type DirectoryContentResult = __Infer<typeof DirectoryContentResult>;

export const DocChunk = __t.object("DocChunk", {
  id: __t.string(),
  documentId: __t.string(),
  content: __t.string(),
  chunkIndex: __t.u32(),
  embeddingJson: __t.string(),
  createdAt: __t.i64(),
});
export type DocChunk = __Infer<typeof DocChunk>;

export const Document = __t.object("Document", {
  id: __t.string(),
  workspaceId: __t.string(),
  title: __t.string(),
  content: __t.string(),
  contentType: __t.string(),
  filePath: __t.string(),
  sourceUrl: __t.string(),
  metadataJson: __t.string(),
  chunkCount: __t.u32(),
  createdAt: __t.i64(),
  updatedAt: __t.i64(),
});
export type Document = __Infer<typeof Document>;

export const EntityLink = __t.object("EntityLink", {
  id: __t.string(),
  workspaceId: __t.string(),
  entityName: __t.string(),
  aliasesJson: __t.string(),
  entityType: __t.string(),
  description: __t.string(),
  createdAt: __t.i64(),
});
export type EntityLink = __Infer<typeof EntityLink>;

export const GodNode = __t.object("GodNode", {
  id: __t.string(),
  workspaceId: __t.string(),
  nodeId: __t.string(),
  edgeCount: __t.u64(),
  computedAt: __t.i64(),
});
export type GodNode = __Infer<typeof GodNode>;

export const HybridResult = __t.object("HybridResult", {
  id: __t.string(),
  workspaceId: __t.string(),
  queryHash: __t.string(),
  entityType: __t.string(),
  entityId: __t.string(),
  content: __t.string(),
  score: __t.f64(),
  strategy: __t.string(),
  createdAt: __t.i64(),
});
export type HybridResult = __Infer<typeof HybridResult>;

export const Insight = __t.object("Insight", {
  id: __t.string(),
  workspaceId: __t.string(),
  peerId: __t.string(),
  content: __t.string(),
  insightType: __t.string(),
  sourceMemoryIdsJson: __t.string(),
  confidence: __t.f64(),
  createdAt: __t.i64(),
});
export type Insight = __Infer<typeof Insight>;

export const KgCommunity = __t.object("KgCommunity", {
  id: __t.u64(),
  workspaceId: __t.string(),
  name: __t.string(),
  summary: __t.string(),
  createdAt: __t.i64(),
});
export type KgCommunity = __Infer<typeof KgCommunity>;

export const KgEdge = __t.object("KgEdge", {
  id: __t.string(),
  workspaceId: __t.string(),
  sourceNodeId: __t.string(),
  targetNodeId: __t.string(),
  relation: __t.string(),
  weight: __t.f64(),
  confidence: __t.string(),
  metadataJson: __t.string(),
  createdAt: __t.i64(),
});
export type KgEdge = __Infer<typeof KgEdge>;

export const KgNode = __t.object("KgNode", {
  id: __t.string(),
  workspaceId: __t.string(),
  label: __t.string(),
  nodeType: __t.string(),
  summary: __t.string(),
  metadataJson: __t.string(),
  communityId: __t.u64(),
  embeddingJson: __t.string(),
  createdAt: __t.i64(),
});
export type KgNode = __Infer<typeof KgNode>;

export const MaintenanceSchedule = __t.object("MaintenanceSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MaintenanceSchedule = __Infer<typeof MaintenanceSchedule>;

export const Memory = __t.object("Memory", {
  id: __t.string(),
  workspaceId: __t.string(),
  peerId: __t.string(),
  observerId: __t.string(),
  memoryType: __t.string(),
  content: __t.string(),
  summary: __t.string(),
  entitiesJson: __t.string(),
  confidence: __t.f64(),
  sourceSessionId: __t.string(),
  sourceMessageId: __t.string(),
  isActive: __t.bool(),
  createdAt: __t.i64(),
  expiresAt: __t.i64(),
  updatedAt: __t.i64(),
  tier: __t.string(),
  accessCount: __t.u64(),
  strength: __t.f64(),
  version: __t.u32(),
  validFrom: __t.i64(),
  parentDirectoryId: __t.string(),
  consolidatedTo: __t.string(),
  trustScore: __t.f64(),
  feedbackCount: __t.u32(),
});
export type Memory = __Infer<typeof Memory>;

export const MemoryFeedback = __t.object("MemoryFeedback", {
  id: __t.string(),
  memoryId: __t.string(),
  rating: __t.string(),
  peerId: __t.string(),
  createdAt: __t.i64(),
});
export type MemoryFeedback = __Infer<typeof MemoryFeedback>;

export const MemoryTag = __t.object("MemoryTag", {
  memoryId: __t.string(),
  tagId: __t.string(),
});
export type MemoryTag = __Infer<typeof MemoryTag>;

export const Message = __t.object("Message", {
  id: __t.string(),
  sessionId: __t.string(),
  senderId: __t.string(),
  content: __t.string(),
  contentType: __t.string(),
  metadata: __t.string(),
  createdAt: __t.i64(),
});
export type Message = __Infer<typeof Message>;

export const Peer = __t.object("Peer", {
  id: __t.string(),
  workspaceId: __t.string(),
  name: __t.string(),
  peerType: __t.string(),
  metadata: __t.string(),
  createdAt: __t.i64(),
  updatedAt: __t.i64(),
});
export type Peer = __Infer<typeof Peer>;

export const PeerSummaryResult = __t.object("PeerSummaryResult", {
  id: __t.string(),
  peerId: __t.string(),
  memoryCount: __t.u64(),
  insightCount: __t.u64(),
  sessionCount: __t.u64(),
  latestActivity: __t.i64(),
});
export type PeerSummaryResult = __Infer<typeof PeerSummaryResult>;

export const Profile = __t.object("Profile", {
  id: __t.string(),
  peerId: __t.string(),
  staticFactsJson: __t.string(),
  dynamicContextJson: __t.string(),
  preferencesJson: __t.string(),
  tagsJson: __t.string(),
  updatedAt: __t.i64(),
});
export type Profile = __Infer<typeof Profile>;

export const ProfileContextResult = __t.object("ProfileContextResult", {
  id: __t.string(),
  peerId: __t.string(),
  staticFactsJson: __t.string(),
  dynamicContextJson: __t.string(),
  preferencesJson: __t.string(),
  tagsJson: __t.string(),
  queryText: __t.string(),
  createdAt: __t.i64(),
});
export type ProfileContextResult = __Infer<typeof ProfileContextResult>;

export const SearchIndex = __t.object("SearchIndex", {
  id: __t.string(),
  workspaceId: __t.string(),
  entityType: __t.string(),
  entityId: __t.string(),
  content: __t.string(),
  embeddingJson: __t.string(),
  bm25Text: __t.string(),
  tokens: __t.u32(),
  createdAt: __t.i64(),
});
export type SearchIndex = __Infer<typeof SearchIndex>;

export const Session = __t.object("Session", {
  id: __t.string(),
  workspaceId: __t.string(),
  name: __t.string(),
  summary: __t.string(),
  metadata: __t.string(),
  createdAt: __t.i64(),
  updatedAt: __t.i64(),
});
export type Session = __Infer<typeof Session>;

export const SessionParticipant = __t.object("SessionParticipant", {
  sessionId: __t.string(),
  peerId: __t.string(),
  role: __t.string(),
  joinedAt: __t.i64(),
});
export type SessionParticipant = __Infer<typeof SessionParticipant>;

export const Tag = __t.object("Tag", {
  id: __t.string(),
  workspaceId: __t.string(),
  name: __t.string(),
  color: __t.string(),
  createdAt: __t.i64(),
});
export type Tag = __Infer<typeof Tag>;

export const Workspace = __t.object("Workspace", {
  id: __t.string(),
  name: __t.string(),
  description: __t.string(),
  createdAt: __t.i64(),
  updatedAt: __t.i64(),
});
export type Workspace = __Infer<typeof Workspace>;

