"""Command modules for the stmem CLI.

Importing each module registers its click group/commands onto the root
``cli`` group (decorators run at import time). Import order matches the
original monolithic stmem.py layout.
"""

from . import (
    completion,
    alias,
    workspace,
    apikey,
    space,
    peer,
    memory,
    decay,
    encryption,
    recommend,
    detect_patterns,
    directory,
    profile,
    fact,
    kg,
    session,
    ingest,
    export,
    compounder,
    wiki_pages,
    connector,
    harmonic,
    shmr,
    context,
    plugin,
    replication,
    mental,
    agent,
    org,
    metrics,
    admin,
    diagnostics,
    synthesize,
    backup,
    serve,
    veracity,
    tag,
    aaak,
    tantivy,
    entity,
)

__all__ = [
    "completion",
    "alias",
    "workspace",
    "apikey",
    "space",
    "peer",
    "memory",
    "decay",
    "encryption",
    "recommend",
    "detect_patterns",
    "directory",
    "profile",
    "fact",
    "kg",
    "session",
    "ingest",
    "export",
    "compounder",
    "wiki_pages",
    "connector",
    "harmonic",
    "shmr",
    "context",
    "plugin",
    "replication",
    "mental",
    "agent",
    "org",
    "metrics",
    "admin",
    "diagnostics",
    "synthesize",
    "backup",
    "serve",
    "veracity",
    "tag",
    "aaak",
    "tantivy",
    "entity",
]
