"""Private helper methods for :class:`Compounder`.

Extracted from the original single-file ``compounder.py`` module.
``CompounderHelpers`` is a mixin — it has no ``__init__`` and expects
``self._client`` and ``self._llm`` to be set by
:class:`~spacetime_memory.compounder.core.Compounder`.
"""

from __future__ import annotations

import datetime
import json
import logging
from typing import Any

logger = logging.getLogger(__name__)


class CompounderHelpers:
    """Mixin holding the private helper methods of ``Compounder``."""

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _generate_title(self, query: str, answer: str) -> str:
        """Generate a concise title from the query or first line of answer."""
        # Use query if it's short enough
        if len(query) < 80:
            return query.strip().rstrip("?.")
        # Otherwise use first line of answer
        first_line = answer.strip().split("\n")[0]
        return first_line[:80].rstrip("?.")

    def _resolve_created_note(
        self,
        workspace_id: str,
        title: str,
        create_result: dict[str, Any],
    ) -> dict[str, Any]:
        """Resolve the full note record after creation.

        The ``create_note`` reducer returns ``{"status": "ok"}``, not the
        note data.  This helper queries the note back by title so callers
        get the real note dict with ``id``, ``created_at``, etc.

        Falls back to returning the original result if the query fails.
        """
        if create_result.get("status") == "ok" and title:
            try:
                matches = self._client.get_note_by_title(title, workspace_id=workspace_id)
                if matches:
                    return matches[0]
                # Fallback: scan recent notes
                all_notes = self._client._query(
                    "note",
                    workspace_id=workspace_id,
                    filter_dict={},
                )
                for n in sorted(all_notes, key=lambda r: r.get("created_at", 0), reverse=True):
                    if n.get("title", "") == title:
                        return n
            except RuntimeError:
                pass
        return create_result

    def _format_answer_page(
        self,
        query: str,
        answer: str,
        source_ids: list[str] | None = None,
    ) -> str:
        """Format the answer as a structured markdown page."""
        parts = [
            f"## Question\n\n{query}\n\n",
            f"## Synthesis\n\n{answer}\n\n",
        ]
        if source_ids:
            refs = "\n".join(f"- `{sid}`" for sid in source_ids)
            parts.append(f"## Sources\n\n{refs}\n")
        parts.append("---\n*Auto-generated by Compounder*")
        return "\n".join(parts)

    def _update_index(
        self,
        workspace_id: str,
        title: str,
        note: dict[str, Any],
        summary: str = "",
    ) -> None:
        """Append an entry to the workspace index note (or create one).

        Each entry follows Karpathy's format:
        ``- [Title](note_id) — one-line summary``

        If no summary is provided, the first line of the note content
        is used as a fallback.
        """
        index_title = "_index"
        note_id = note.get("id", "")

        # Generate summary from note content if not provided
        if not summary:
            content = note.get("content", "")
            if content:
                # Try first non-empty, non-separator line
                for line in content.split("\n"):
                    stripped = line.strip()
                    if stripped and not stripped.startswith("---") and not stripped.startswith("#"):
                        summary = stripped[:120].rstrip(".")
                        break

        summary_suffix = ""
        if summary:
            summary_suffix = f" — {summary}"

        link = f"- [{title}]({note_id}){summary_suffix}\n"

        existing = self._client._query(
            "note",
            workspace_id=workspace_id,
            filter_dict={"title": index_title},
        )

        if existing:
            # Append to existing index
            idx_note = existing[0]
            new_content = idx_note.get("content", "") + link
            try:
                self._client.update_note(
                    note_id=idx_note.get("id", ""),
                    title=index_title,
                    content=new_content,
                    embed=False,
                )
            except RuntimeError:
                pass
        else:
            # Create index note
            header = "# Workspace Index\n\nAuto-generated index of synthesis pages.\n\n"
            try:
                self._client.create_note(
                    workspace_id=workspace_id,
                    title=index_title,
                    content=header + link,
                    embed=False,
                )
            except RuntimeError:
                pass

    def _already_linked(self, id1: str, id2: str, workspace_id: str = "") -> bool:
        """Check whether two entities are already linked in the KG."""
        edges = self._client._query(
            "kg_edge",
            workspace_id=workspace_id,
            filter_dict={},
        )
        for e in edges:
            src = e.get("source_node_id", "")
            tgt = e.get("target_node_id", "")
            if (src == id1 and tgt == id2) or (src == id2 and tgt == id1):
                return True
        return False

    def _node_label(self, node_id: str, nodes: list[dict]) -> str:
        """Look up the label for a KG node by ID."""
        for n in nodes:
            if n.get("id") == node_id:
                return n.get("label", node_id)
        return node_id[:12]

    # ------------------------------------------------------------------
    # Ripple update — update entity summary with new information
    # ------------------------------------------------------------------

    def _ripple_update_entity(
        self,
        workspace_id: str,
        entity_name: str,
        new_information: str,
        source_note_id: str,
    ) -> None:
        """Find an existing KG node for *entity_name* and update its
        summary to incorporate *new_information* (if LLM available).

        Gracefully degrades when the LLM is not configured — simply
        skips the update.
        """
        if not entity_name.strip():
            return
        if not self._llm.available:
            return

        # Find the node
        nodes = self._client._query(
            "kg_node",
            workspace_id=workspace_id,
            filter_dict={"label": entity_name},
        )
        if not nodes:
            return

        node = nodes[-1]
        node_id = node.get("id", "")
        existing_summary = node.get("summary", "")

        # Use LLM to merge the new info into existing summary
        if existing_summary:
            prompt = (
                f"Existing summary: {existing_summary}\n\n"
                f"New information: {new_information[:1000]}\n\n"
                "Merge the new information into a concise updated summary "
                f"for '{entity_name}'. Keep it to 2-3 sentences."
                " Return ONLY the updated summary text, no explanation."
            )
        else:
            prompt = (
                f"Summarize this information about '{entity_name}' in "
                f"2-3 sentences:\n\n{new_information[:1000]}"
            )

        new_summary = self._llm.summarize(prompt)
        if new_summary and new_summary != existing_summary:
            try:
                self._client._call(
                    "update_node",
                    [
                        node_id,
                        entity_name,
                        node.get("node_type", "concept"),
                        new_summary,
                        "{}",
                        source_note_id,
                    ],
                )
                logger.info(
                    "Ripple-updated node '%s' (%s) with new summary",
                    entity_name,
                    node_id[:12],
                )
            except RuntimeError:
                pass

    # ------------------------------------------------------------------
    # Chronological log (_log note)
    # ------------------------------------------------------------------

    def _log_activity(
        self,
        workspace_id: str,
        event_type: str,
        detail: str,
    ) -> None:
        """Append a timestamped entry to the workspace chronological log.

        Creates a ``_log`` note if one doesn't exist.  Each entry uses a
        parseable prefix: ``## [YYYY-MM-DD] event_type | detail`` so the
        log is searchable with simple tools like ``grep``.
        """
        log_title = "_log"
        now = datetime.datetime.now(datetime.UTC).strftime("%Y-%m-%d %H:%M UTC")
        entry = f"## [{now}] {event_type} | {detail}\n"

        existing = self._client._query(
            "note",
            workspace_id=workspace_id,
            filter_dict={"title": log_title},
        )
        if existing:
            idx_note = existing[0]
            new_content = idx_note.get("content", "") + entry
            try:
                self._client.update_note(
                    note_id=idx_note.get("id", ""),
                    title=log_title,
                    content=new_content,
                    embed=False,
                )
            except RuntimeError:
                pass
        else:
            header = "# Workspace Log\n\nChronological record of compounder activity.\n\n"
            try:
                self._client.create_note(
                    workspace_id=workspace_id,
                    title=log_title,
                    content=header + entry,
                    embed=False,
                )
            except RuntimeError:
                pass

    def _find_orphan_nodes(self, workspace_id: str) -> list[dict[str, Any]]:
        """Find KG nodes with no edges to any other node."""
        nodes = self._client._query(
            "kg_node",
            workspace_id=workspace_id,
            filter_dict={},
        )
        edges = self._client._query(
            "kg_edge",
            workspace_id=workspace_id,
            filter_dict={},
        )
        connected: set[str] = set()
        for e in edges:
            src = e.get("source_node_id", "")
            tgt = e.get("target_node_id", "")
            if src:
                connected.add(src)
            if tgt:
                connected.add(tgt)

        orphans = []
        for n in nodes:
            nid = n.get("id", "")
            if nid and nid not in connected:
                orphans.append(
                    {
                        "id": nid,
                        "label": n.get("label", nid[:12]),
                        "node_type": n.get("node_type", "unknown"),
                    }
                )
        return orphans

    def _find_missing_crossrefs(
        self,
        workspace_id: str,
        limit: int = 100,
    ) -> list[dict[str, Any]]:
        """Find notes/memories whose content mentions a KG node label
        but has no edge to that node."""
        # Get all KG nodes and their labels
        nodes = self._client._query(
            "kg_node",
            workspace_id=workspace_id,
            filter_dict={},
        )
        # Get all edges to know what's already connected
        edges = self._client._query(
            "kg_edge",
            workspace_id=workspace_id,
            filter_dict={},
        )
        # Also track which memory IDs are linked to which nodes
        mem_to_node: dict[str, set[str]] = {}
        for e in edges:
            src = e.get("source_node_id", "")
            tgt = e.get("target_node_id", "")
            if src:
                mem_to_node.setdefault(src, set()).add(tgt)
            if tgt:
                mem_to_node.setdefault(tgt, set()).add(src)

        # Build a map of labels → node IDs
        label_map: dict[str, str] = {}
        for n in nodes:
            label = (n.get("label", "") or "").lower().strip()
            if label:
                label_map[label] = n.get("id", "")

        if not label_map:
            return []

        # Scan memories and notes
        missing: list[dict[str, Any]] = []
        memories = self._client._query(
            "memory",
            workspace_id=workspace_id,
            filter_dict={},
        )[:limit]
        notes = self._client._query(
            "note",
            workspace_id=workspace_id,
            filter_dict={},
        )[:limit]

        for mem in memories:
            content = (mem.get("content", "") or "").lower()
            mid = mem.get("id", "")
            if not content or not mid:
                continue
            for label_lower, node_id in label_map.items():
                if label_lower in content:
                    # Check if already linked
                    if node_id not in mem_to_node.get(mid, set()):
                        missing.append(
                            {
                                "entity_id": mid,
                                "entity_type": "memory",
                                "mentioned_label": label_lower,
                                "target_node_id": node_id,
                            }
                        )

        for note in notes:
            content = (note.get("content", "") or "").lower()
            nid = note.get("id", "")
            if not content or not nid:
                continue
            for label_lower, node_id in label_map.items():
                if label_lower in content:
                    if node_id not in mem_to_node.get(nid, set()):
                        missing.append(
                            {
                                "entity_id": nid,
                                "entity_type": "note",
                                "mentioned_label": label_lower,
                                "target_node_id": node_id,
                            }
                        )

        return missing

    def _find_note_orphans(
        self,
        workspace_id: str,
        limit: int = 100,
    ) -> list[dict[str, Any]]:
        """Find notes entirely disconnected from the knowledge graph.

        A note is considered an orphan if:
        1. Its content/title mentions no known KG node labels.
        2. Its ID does not appear in any KG edge (source or target).

        Returns:
            List of note dicts with ``id``, ``title``, ``reason``.
        """
        notes = self._client._query(
            "note",
            workspace_id=workspace_id,
            filter_dict={},
        )[:limit]
        if not notes:
            return []

        # Get KG node labels for content-matching
        nodes = self._client._query(
            "kg_node",
            workspace_id=workspace_id,
            filter_dict={},
        )
        label_map: dict[str, str] = {}
        for n in nodes:
            label = (n.get("label", "") or "").lower().strip()
            if label:
                label_map[label] = n.get("id", "")

        # Get all edges to check which IDs are connected
        edges = self._client._query(
            "kg_edge",
            workspace_id=workspace_id,
            filter_dict={},
        )
        connected_ids: set[str] = set()
        for e in edges:
            src = e.get("source_node_id", "")
            tgt = e.get("target_node_id", "")
            if src:
                connected_ids.add(src)
            if tgt:
                connected_ids.add(tgt)

        orphans: list[dict[str, Any]] = []
        for note in notes:
            note_id = note.get("id", "")
            if not note_id:
                continue
            # Check if note is connected via edges
            if note_id in connected_ids:
                continue
            # Check if note content/title mentions any KG label
            content = (note.get("content", "") or "").lower()
            title = (note.get("title", "") or "").lower()
            combined = f"{title} {content}"
            mentions_entity = any(label in combined for label in label_map)
            if mentions_entity:
                continue
            # Note is disconnected from KG
            orphans.append(
                {
                    "id": note_id,
                    "title": note.get("title", "untitled"),
                    "reason": "Note content and title mention no KG entities, "
                    "and note has no edges to the KG.",
                }
            )

        return orphans

    def _find_contradictions(
        self,
        workspace_id: str,
        limit: int = 50,
    ) -> list[dict[str, Any]]:
        """Use LLM to find contradictory claims between semantically
        similar memories.

        Works in pairs: groups memories by semantic similarity, then
        asks the LLM whether each pair contains contradictory claims.

        Returns:
            List of contradiction dicts with ``id_a``, ``id_b``,
            ``content_a``, ``content_b``, ``explanation``.
        """
        if not self._llm.available:
            return []

        memories = self._client._query(
            "memory",
            workspace_id=workspace_id,
            filter_dict={},
        )
        if len(memories) < 2:
            return []

        # Take the most recent N
        memories = sorted(memories, key=lambda r: r.get("created_at", 0), reverse=True)[:limit]

        contradictions: list[dict[str, Any]] = []
        checked = 0

        for i in range(min(len(memories), 10)):  # Limit pairs to avoid LLM flood
            for j in range(i + 1, min(len(memories), i + 3)):  # Adjacent pairs
                mem_a = memories[i]
                mem_b = memories[j]
                content_a = mem_a.get("content", "")
                content_b = mem_b.get("content", "")
                if not content_a or not content_b:
                    continue

                checked += 1
                prompt = (
                    f"Memory A: {content_a[:500]}\n\n"
                    f"Memory B: {content_b[:500]}\n\n"
                    "Do these two statements contain contradictory claims? "
                    "Reply with a JSON object: "
                    '{"is_contradiction": bool, "explanation": str}. '
                    "Return ONLY valid JSON, no markdown."
                )
                result = self._llm.chat(
                    [{"role": "user", "content": prompt}],
                    response_format={"type": "json_object"},
                    temperature=0.1,
                    max_tokens=256,
                )
                if not result:
                    continue
                try:
                    data = json.loads(result)
                    if data.get("is_contradiction"):
                        contradictions.append(
                            {
                                "id_a": mem_a.get("id", ""),
                                "id_b": mem_b.get("id", ""),
                                "content_a": content_a[:200],
                                "content_b": content_b[:200],
                                "explanation": data.get("explanation", ""),
                            }
                        )
                except (json.JSONDecodeError, TypeError):
                    continue

        self._log_activity(
            workspace_id,
            "contradiction_check",
            f"Checked {checked} pairs, found {len(contradictions)} contradictions",
        )
        return contradictions

    def _create_contradiction_notes(
        self,
        workspace_id: str,
        contradictions: list[dict[str, Any]],
    ) -> None:
        """Create notes documenting each contradiction found during lint.

        Each note records the two conflicting memories and the LLM's
        explanation, helping the user review and resolve the conflict.
        """
        for i, c in enumerate(contradictions):
            title = f"Contradiction #{i + 1}: {c.get('id_a', '?')[:8]} ↔ {c.get('id_b', '?')[:8]}"
            content = (
                f"## Contradiction Detected\n\n"
                f"**Memory A**: `{c.get('id_a', '')}`\n"
                f"> {c.get('content_a', '')}\n\n"
                f"**Memory B**: `{c.get('id_b', '')}`\n"
                f"> {c.get('content_b', '')}\n\n"
                f"**Explanation**: {c.get('explanation', 'No explanation provided.')}\n\n"
                f"---\n*Auto-detected by Compounder lint*"
            )
            try:
                self._client.create_note(
                    workspace_id=workspace_id,
                    title=title,
                    content=content,
                    embed=True,
                )
            except RuntimeError:
                continue

    def _format_source_page(
        self,
        title: str,
        full_text: str,
        summary: str,
        source_type: str,
    ) -> str:
        """Format a source document as a structured markdown page."""
        max_preview = 2000
        body_preview = full_text[:max_preview]
        if len(full_text) > max_preview:
            body_preview += "\n\n*[truncated — full source has "
            body_preview += f"{len(full_text)} chars]*"

        return (
            f"## Summary\n\n{summary}\n\n"
            f"## Source ({source_type}): {title}\n\n"
            f"{body_preview}\n\n"
            f"---\n*Auto-imported via ingest_source*"
        )

    # ------------------------------------------------------------------
    # Proactive contradiction detection (called during ingest)
    # ------------------------------------------------------------------

    def _check_contradictions_on_ingest(
        self,
        workspace_id: str,
        new_content: str,
        source_note_id: str,
        limit: int = 20,
    ) -> list[dict[str, Any]]:
        """Check if new source content contradicts existing memories.

        Searches for semantically similar existing memories, then asks
        the LLM whether each pair contains contradictory claims.

        Args:
            workspace_id: Target workspace.
            new_content: The new source content to check.
            source_note_id: The note ID of the newly ingested source
                (used to link contradiction notes back).
            limit: Max existing memories to check against.

        Returns:
            List of contradiction dicts with ``memory_id``,
            ``existing_content``, ``explanation``.
        """
        if not self._llm.available or not new_content.strip():
            return []

        # Find semantically similar existing memories
        similar = self._client.search(
            workspace_id,
            new_content[:1000],
            limit=limit,
            semantic=True,
            memory_type="",
            tier="",
        )
        if not similar:
            return []

        contradictions: list[dict[str, Any]] = []
        for match in similar[:5]:  # Check top 5
            existing_id = match.get("entity_id", "")
            existing_content = match.get("content", "")
            if not existing_id or not existing_content:
                continue

            prompt = (
                f"New information: {new_content[:800]}\n\n"
                f"Existing knowledge: {existing_content[:800]}\n\n"
                "Do these two statements contain contradictory claims? "
                "Reply with a JSON object: "
                '{"is_contradiction": bool, "explanation": str}. '
                "Return ONLY valid JSON, no markdown."
            )
            result = self._llm.chat(
                [{"role": "user", "content": prompt}],
                response_format={"type": "json_object"},
                temperature=0.1,
                max_tokens=256,
            )
            if not result:
                continue
            try:
                data = json.loads(result)
                if data.get("is_contradiction"):
                    contradictions.append(
                        {
                            "memory_id": existing_id,
                            "existing_content": existing_content[:200],
                            "explanation": data.get("explanation", ""),
                        }
                    )
                    # Create a contradiction note linking source to existing
                    self._create_ingest_contradiction_note(
                        workspace_id,
                        source_note_id,
                        existing_id,
                        data.get("explanation", ""),
                    )
            except (json.JSONDecodeError, TypeError):
                continue

        if contradictions:
            self._log_activity(
                workspace_id,
                "contradiction_on_ingest",
                f"Found {len(contradictions)} contradictions with existing knowledge",
            )

        return contradictions

    def _create_ingest_contradiction_note(
        self,
        workspace_id: str,
        new_note_id: str,
        existing_memory_id: str,
        explanation: str,
    ) -> None:
        """Create a note documenting a contradiction found during ingest."""
        title = f"Contradiction: new source ↔ {existing_memory_id[:8]}"
        content = (
            f"## Contradiction Detected During Ingest\n\n"
            f"**New source**: `{new_note_id}`\n"
            f"**Existing memory**: `{existing_memory_id}`\n\n"
            f"**Explanation**: {explanation}\n\n"
            f"---\n*Auto-detected during ingest_source*"
        )
        try:
            self._client.create_note(
                workspace_id=workspace_id,
                title=title,
                content=content,
                embed=True,
            )
        except RuntimeError:
            pass
